// Code generated by mss-protoc-gen. DO NOT EDIT.

import type { Hono } from "hono";


import { UserRestHandler } from "../handler/user-handler.gen.js";
import type { UserUsecase } from "../usecase/user-usecase-interface.gen.js";


// handler-registry は main.ts が必要とする Usecase 依存を一覧で宣言する。
export type HandlerDeps = {
  userUsecase: UserUsecase;
};

// Hono アプリに全サービスの REST ルートを登録する。
export function registerHandlers(app: Hono, deps: HandlerDeps): void {
  const userHandler = new UserRestHandler(deps.userUsecase);
  app.post("/api/users", (c) => userHandler.createUser(c));
  app.get("/api/users/:id", (c) => userHandler.getUser(c));
}
