// Code generated by mss-protoc-gen. DO NOT EDIT.

import type { Hono } from "hono";


import { UserRestHandler } from "../handler/user-handler.gen.js";
import type { UserUsecase } from "../usecase/user-usecase-interface.gen.js";


// handler-registry は main.ts が必要とする Usecase 依存を一覧で宣言する。
export type HandlerDeps = {
  userUsecase: UserUsecase;
};

// Hono アプリに全サービスの REST ルートを登録する。
export function registerHandlers(app: Hono, deps: HandlerDeps): void {
  const userHandler = new UserRestHandler(deps.userUsecase);
  app.get("/api/users", (c) => userHandler.listUsers(c));
  app.get("/api/users/cursor", (c) => userHandler.listUsersByCursor(c));
  app.get("/api/users/by-email", (c) => userHandler.getUserByEmail(c));
  app.get("/api/users/:id", (c) => userHandler.getUser(c));
  app.post("/api/users", (c) => userHandler.createUser(c));
  app.post("/api/users/bulk", (c) => userHandler.bulkCreateUsers(c));
  app.put("/api/users/bulk", (c) => userHandler.bulkUpsertUsers(c));
  app.put("/api/users/:id", (c) => userHandler.upsertUser(c));
  app.patch("/api/users/:id", (c) => userHandler.updateUser(c));
  app.post("/api/users/bulk-delete", (c) => userHandler.bulkDeleteUsers(c));
  app.delete("/api/users/:id", (c) => userHandler.deleteUser(c));
  app.delete("/api/users", (c) => userHandler.deleteAllUsers(c));
}
