// Code generated by mss-protoc-gen. DO NOT EDIT.

package di

import (
	"net/http"

	"github.com/example/manji-standard-server-go/internal/handler"
	"github.com/example/manji-standard-server-go/internal/usecase"
)

// Handlers は全サービスの REST Handler を束ねた DI コンテナ。
type Handlers struct {
	UserService *handler.UserHandler
}

// NewHandlers は各 Usecase を受け取って Handlers を組み立てる。
func NewHandlers(
	userUsecase usecase.UserUsecase,
) *Handlers {
	return &Handlers{
		UserService: handler.NewUserHandler(userUsecase),
	}
}

// Register は全 Handler を ServeMux に登録する（Go 1.22+ の HandleFunc パターン）。
func (h *Handlers) Register(mux *http.ServeMux) {
	mux.HandleFunc("GET /api/users", h.UserService.ListUsers)
	mux.HandleFunc("GET /api/users/cursor", h.UserService.ListUsersByCursor)
	mux.HandleFunc("GET /api/users/by-email", h.UserService.GetUserByEmail)
	mux.HandleFunc("GET /api/users/{id}", h.UserService.GetUser)
	mux.HandleFunc("POST /api/users", h.UserService.CreateUser)
	mux.HandleFunc("POST /api/users/bulk", h.UserService.BulkCreateUsers)
	mux.HandleFunc("PUT /api/users/bulk", h.UserService.BulkUpsertUsers)
	mux.HandleFunc("PUT /api/users/{id}", h.UserService.UpsertUser)
	mux.HandleFunc("PATCH /api/users/{id}", h.UserService.UpdateUser)
	mux.HandleFunc("POST /api/users/bulk-delete", h.UserService.BulkDeleteUsers)
	mux.HandleFunc("DELETE /api/users/{id}", h.UserService.DeleteUser)
	mux.HandleFunc("DELETE /api/users", h.UserService.DeleteAllUsers)
}
