syntax = "proto3";

package user.v1;

// @entity
message User {
  // @pk
  string id = 1;
  // @unique @email
  string email = 2;
  // @required
  string name = 3;
  // @timestamp
  int64 created_at_unix = 4;
}

message CreateUserRequest {
  string email = 1;
  string name = 2;
}

message CreateUserResponse {
  User user = 1;
}

message GetUserRequest {
  string id = 1;
}

message GetUserResponse {
  User user = 1;
}

service UserService {
  // @http POST /api/users
  rpc CreateUser(CreateUserRequest) returns (CreateUserResponse);

  // @http GET /api/users/{id}
  rpc GetUser(GetUserRequest) returns (GetUserResponse);
}
