// Code generated by mss-protoc-gen. DO NOT EDIT.

"use client";
import { useState } from "react";
import { UserList } from "../../gen/ui/user/UserList";
import { UserForm } from "../../gen/ui/user/UserForm";

export default function UsersPage() {
  const [k, setK] = useState(0);
  return (
    <main style={{ maxWidth: 640, margin: "2rem auto", fontFamily: "system-ui" }}>
      <h1>Users</h1>
      <UserForm onCreated={() => setK((x) => x + 1)} />
      <hr style={{ margin: "1rem 0" }} />
      <UserList key={k} />
    </main>
  );
}
