// Code generated by mss-protoc-gen. DO NOT EDIT.

import { UserList } from "../../gen/ui/user/UserList";

export default function UsersPage() {
  return (<main style={{ maxWidth: 640, margin: "2rem auto", fontFamily: "system-ui" }}><h1>Users</h1><UserList /></main>);
}
