// Code generated by mss-protoc-gen. DO NOT EDIT.

import Link from "next/link";
import { UserList } from "../../gen/ui/user/UserList";
import { Page } from "../../lib/widgets";

export default function UsersPage() {
  return (<Page title="Users" actions={<Link href="/users/new">+ New</Link>}><UserList /></Page>);
}
