# Code generated by mss-protoc-gen. DO NOT EDIT.
from __future__ import annotations
from fastapi import FastAPI
from app.handler.user_handler import new_user_router


def register_routers(
    app: FastAPI,
    *,
    user_usecase,
) -> None:
    app.include_router(new_user_router(user_usecase))
