// Code generated by mss-protoc-gen. DO NOT EDIT.

import type { {{.Name}} } from "../domain/entity/{{.Kebab}}.gen.js";

/**
 * {{.Name}}DTO は {{.Name}} エンティティをクライアントへ返すための JSON シリアライズ型。
 * snake_case のキーで wire format を表す。entity 側は ORM タグ + バリデーションのみを持ち、
 * クライアント返却型は DTO 層で一元管理する。
 */
export type {{.Name}}DTO = {
{{- range .Fields}}
{{- if .isTimestamp}}
  {{.snakeName}}_unix: number;
{{- else}}
  {{.snakeName}}: {{.type}};
{{- end}}
{{- end}}
};

export function from{{.Name}}(e: {{.Name}}): {{.Name}}DTO {
  return {
{{- range .Fields}}
{{- if .isTimestamp}}
    {{.snakeName}}_unix: Math.floor(e.{{.name}}.getTime() / 1000),
{{- else}}
    {{.snakeName}}: e.{{.name}},
{{- end}}
{{- end}}
  };
}

export function from{{.Name}}s(es: {{.Name}}[]): {{.Name}}DTO[] {
  return es.map(from{{.Name}});
}
