// Code generated by mss-protoc-gen. DO NOT EDIT.

import { UserDetail } from "../../../gen/ui/user/UserDetail";

export default function UserDetailPage({ params }: { params: { id: string } }) {
  return (<main style={{ maxWidth: 640, margin: "2rem auto", fontFamily: "system-ui" }}><UserDetail id={params.id} /></main>);
}
