// Code generated by mss-protoc-gen. DO NOT EDIT.

import { UserDetail } from "../../../gen/ui/user/UserDetail";
import { Page } from "../../../lib/widgets";

export default function UserDetailPage({ params }: { params: { id: string } }) {
  return (<Page title="User"><UserDetail id={params.id} /></Page>);
}
