# Code generated by mss-protoc-gen. DO NOT EDIT.
from __future__ import annotations
from sqlalchemy import select, delete as sql_delete
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.exc import IntegrityError
from app.infra.db import tx
from app.domain.entity.user import User
from app.domain.repository.user_repository import (
    UserNotFoundError,
    UserAlreadyExistsError,
)


class PostgresUserRepository:
    def select_all(self) -> list[User]:
        q = select(User)
        return list(tx.session().scalars(q).all())

    def select_by_pk(self, id) -> User | None:
        return tx.session().get(User, id)

    def select_by_email(self, email) -> User | None:
        return tx.session().scalars(
            select(User).where(User.email == email)
        ).first()

    def insert(self, e: User) -> None:
        s = tx.session()
        s.add(e)
        try:
            s.flush()
        except IntegrityError as ex:
            raise UserAlreadyExistsError() from ex

    def bulk_insert(self, es: list[User]) -> None:
        if not es:
            return
        s = tx.session()
        s.add_all(es)
        try:
            s.flush()
        except IntegrityError as ex:
            raise UserAlreadyExistsError() from ex

    def upsert(self, e: User) -> None:
        self._upsert([e])

    def bulk_upsert(self, es: list[User]) -> None:
        if es:
            self._upsert(es)

    def _upsert(self, es: list[User]) -> None:
        cols = ['id', 'email', 'name', 'created_at']
        vals = [{c: getattr(e, c) for c in cols} for e in es]
        stmt = pg_insert(User).values(vals)
        upd = {c: getattr(stmt.excluded, c) for c in cols if c != "id"}
        stmt = stmt.on_conflict_do_update(index_elements=["id"], set_=upd)
        tx.session().execute(stmt)

    def update(self, e: User) -> None:
        s = tx.session()
        obj = s.get(User, e.id)
        if obj is None:
            raise UserNotFoundError()
        obj.email = e.email
        obj.name = e.name
        obj.created_at = e.created_at
        s.flush()

    def delete(self, id) -> None:
        s = tx.session()
        obj = s.get(User, id)
        if obj is None:
            raise UserNotFoundError()
        s.delete(obj)
        s.flush()

    def bulk_delete(self, ids) -> None:
        if not ids:
            return
        stmt = sql_delete(User).where(User.id.in_(ids))
        res = tx.session().execute(stmt)
        if res.rowcount != len(ids):
            raise UserNotFoundError()

    def delete_all(self) -> None:
        tx.session().execute(sql_delete(User))

    def select_by_cursor(self, limit, after) -> list[User]:
        q = select(User).order_by(User.id).limit(limit)
        if after is not None:
            q = q.where(User.id > after)
        return list(tx.session().scalars(q).all())


def new_postgres_user_repository() -> PostgresUserRepository:
    return PostgresUserRepository()


def auto_migrate_user(engine) -> None:
    User.__table__.create(bind=engine, checkfirst=True)
