// Code generated by mss-protoc-gen. DO NOT EDIT.

package di

import (
	"net/http"

	"github.com/example/manji-standard-server-go/pkg/handler"
	"github.com/example/manji-standard-server-go/pkg/usecase"
)

// Handlers は全サービスの REST Handler を束ねた DI コンテナ。
type Handlers struct {
	UserService *handler.UserHandler
}

// NewHandlers は各 Usecase を受け取って Handlers を組み立てる。
func NewHandlers(
	userUsecase usecase.UserUsecase,
) *Handlers {
	return &Handlers{
		UserService: handler.NewUserHandler(userUsecase),
	}
}

// Register は全 Handler を ServeMux に登録する（Go 1.22+ の HandleFunc パターン）。
func (h *Handlers) Register(mux *http.ServeMux) {
	mux.HandleFunc("POST /api/users", h.UserService.CreateUser)
	mux.HandleFunc("GET /api/users/{id}", h.UserService.GetUser)
}
