// Code generated by mss-protoc-gen. DO NOT EDIT.

import type { Hono } from "hono";

{{range .Services}}
import { {{.HandlerClassName}} } from "../handler/{{.Kebab}}-handler.gen.js";
import type { {{.UsecaseTypeName}} } from "../usecase/{{.Kebab}}-usecase-interface.gen.js";
{{end}}

// handler-registry は main.ts が必要とする Usecase 依存を一覧で宣言する。
export type HandlerDeps = {
{{- range .Services}}
  {{.UsecaseVarName}}: {{.UsecaseTypeName}};
{{- end}}
};

// Hono アプリに全サービスの REST ルートを登録する。
export function registerHandlers(app: Hono, deps: HandlerDeps): void {
{{- range .Services}}
  const {{.HandlerVarName}} = new {{.HandlerClassName}}(deps.{{.UsecaseVarName}});
{{- end}}
{{- range .Routes}}
  app.{{.HttpMethodLower}}("{{.HonoPath}}", (c) => {{.HandlerVarName}}.{{.MethodName}}(c));
{{- end}}
}
