// Code generated by mss-protoc-gen. DO NOT EDIT.

import "@/lib/container"; // side-effect: HandlerDeps factory を登録
import { NextResponse } from "next/server";


import {
  UserNotFoundError,
  UserAlreadyExistsError,
} from "@/domain/repository/user-repository.gen";
import { getHandlerDeps } from "@/lib/handler-registry.gen";
import type {
  UserUsecase,
  GetUserInput,
  UpsertUserInput,
  UpdateUserInput,
  DeleteUserInput,
  CreateUserParams,
  UpsertUserParams,
} from "@/usecase/user-usecase-interface.gen";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function toHttpError(err: unknown): NextResponse {
  if (err instanceof UserNotFoundError) return NextResponse.json({ error: err.message }, { status: 404 });
  if (err instanceof UserAlreadyExistsError) return NextResponse.json({ error: err.message }, { status: 409 });
  const message = err instanceof Error ? err.message : "unknown error";
  return NextResponse.json({ error: message }, { status: 400 });
}


export async function GET(
  _req: Request,
  { params }: { params: { id: string; } },
) {
  try {
    const deps = getHandlerDeps();
    const input: GetUserInput = {
      id: params.id,
    };
    const result = await deps.userUsecase.getUser(input);
    if (!result) return NextResponse.json({ error: "user not found" }, { status: 404 });
    return NextResponse.json(result, { status: 200 });
  } catch (err) {
    return toHttpError(err);
  }
}

type UpsertUserBody = {
  email?: string;
  name?: string;
  created_at_unix?: number;
};
export async function PUT(
  req: Request,
  { params }: { params: { id: string; } },
) {
  let body: UpsertUserBody;
  try {
    body = (await req.json()) as UpsertUserBody;
  } catch {
    return NextResponse.json({ error: "invalid body" }, { status: 400 });
  }
  try {
    const deps = getHandlerDeps();
    const input: UpsertUserInput = {
      id: params.id,
      email: body.email ?? "",
      name: body.name ?? "",
      createdAtUnix: body.created_at_unix ?? 0,
    };
    const result = await deps.userUsecase.upsertUser(input);
    if (!result) return NextResponse.json({ error: "user not found" }, { status: 404 });
    return NextResponse.json(result, { status: 200 });
  } catch (err) {
    return toHttpError(err);
  }
}

type UpdateUserBody = {
  email?: string;
  name?: string;
};
export async function PATCH(
  req: Request,
  { params }: { params: { id: string; } },
) {
  let body: UpdateUserBody;
  try {
    body = (await req.json()) as UpdateUserBody;
  } catch {
    return NextResponse.json({ error: "invalid body" }, { status: 400 });
  }
  try {
    const deps = getHandlerDeps();
    const input: UpdateUserInput = {
      id: params.id,
      email: body.email ?? "",
      name: body.name ?? "",
    };
    const result = await deps.userUsecase.updateUser(input);
    if (!result) return NextResponse.json({ error: "user not found" }, { status: 404 });
    return NextResponse.json(result, { status: 200 });
  } catch (err) {
    return toHttpError(err);
  }
}

export async function DELETE(
  _req: Request,
  { params }: { params: { id: string; } },
) {
  try {
    const deps = getHandlerDeps();
    const input: DeleteUserInput = {
      id: params.id,
    };
    await deps.userUsecase.deleteUser(input);
    return new NextResponse(null, { status: 204 });
  } catch (err) {
    return toHttpError(err);
  }
}
