// Code generated by mss-protoc-gen. DO NOT EDIT.

import "@/lib/container"; // side-effect: HandlerDeps factory を登録
import { NextResponse } from "next/server";


import type { User } from "@/domain/entity/user.gen";
import {
  UserNotFoundError,
  UserAlreadyExistsError,
} from "@/domain/repository/user-repository.gen";
import { getHandlerDeps } from "@/lib/handler-registry.gen";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";


function userToJson(e: User) {
  return {
    id: e.id,
    email: e.email,
    name: e.name,
    createdAtUnix: Math.floor(e.createdAt.getTime() / 1000),
  };
}

function toHttpError(err: unknown): NextResponse {
  if (err instanceof UserNotFoundError) return NextResponse.json({ error: err.message }, { status: 404 });
  if (err instanceof UserAlreadyExistsError) return NextResponse.json({ error: err.message }, { status: 409 });
  const message = err instanceof Error ? err.message : "unknown error";
  return NextResponse.json({ error: message }, { status: 400 });
}



export async function GET(
  _req: Request,
  { params }: { params: { id: string; } },
) {
  try {
    const deps = getHandlerDeps();
    const e = await deps.userUsecase.getUser({
      id: params.id,
    });
    if (!e) return NextResponse.json({ error: "user not found" }, { status: 404 });
    return NextResponse.json(userToJson(e), { status: 200 });
  } catch (err) {
    return toHttpError(err);
  }
}
