// Code generated by mss-protoc-gen. DO NOT EDIT.
{{range .UsedEntities}}
import type { {{.Name}}DTO } from "../dto/{{.Kebab}}.gen.js";
{{- end}}

{{range .NonEntityTypes}}
/**
 * {{.Name}} は rpc 入力の非 entity message を TS 型として表したもの。
 * snake_case のキーは proto field 名(クライアント wire format)に揃えてある。
 */
export type {{.Name}} = {
{{- range .Fields}}
  {{.jsonName}}: {{.type}};
{{- end}}
};

{{end}}
{{range .Methods}}
{{- if .HasInputFields}}

export type {{.InputTypeName}} = {
{{- range .InputFields}}
  {{.name}}: {{.type}};
{{- end}}
};
{{- else}}

export type {{.InputTypeName}} = Record<string, never>;
{{- end}}
{{- end}}

/**
 * {{.UsecaseTypeName}} は {{.ServiceName}} の rpc 1 本につき 1 メソッドを持つ interface。
 * 実装クラス({{.UsecaseTypeName}}Impl)はこの interface を実装する手書き層。
 * 戻り値はすべて DTO に変換済み(クライアント JSON 表現の境界)。
 */
export interface {{.UsecaseTypeName}} {
{{- range .Methods}}
{{- if .ReturnsEntity}}
  {{.lowerName}}(input: {{.InputTypeName}}): Promise<{{.EntityName}}DTO | null>;
{{- end}}
{{- if .ReturnsList}}
  {{.lowerName}}(input: {{.InputTypeName}}): Promise<{{.EntityName}}DTO[]>;
{{- end}}
{{- if .ReturnsEmpty}}
  {{.lowerName}}(input: {{.InputTypeName}}): Promise<void>;
{{- end}}
{{- end}}
}
