// Code generated by mss-protoc-gen. DO NOT EDIT.
{{range .UsedEntities}}
import type { {{.Name}} } from "../domain/entity/{{.Kebab}}.gen.js";
{{- end}}
{{range .Methods}}
{{- if .HasInputFields}}

export type {{.InputTypeName}} = {
{{- range .InputFields}}
  {{.name}}: {{.type}};
{{- end}}
};
{{- else}}

export type {{.InputTypeName}} = Record<string, never>;
{{- end}}
{{- end}}

/**
 * {{.UsecaseTypeName}} は {{.ServiceName}} の rpc 1 本につき 1 メソッドを持つ interface。
 * 実装クラス（{{.UsecaseTypeName}}Impl）はこの interface を実装する手書き層。
 */
export interface {{.UsecaseTypeName}} {
{{- range .Methods}}
{{- if .ReturnsEntity}}
  {{.lowerName}}(input: {{.InputTypeName}}): Promise<{{.EntityName}} | null>;
{{- end}}
{{- if .ReturnsList}}
  {{.lowerName}}(input: {{.InputTypeName}}): Promise<{{.EntityName}}[]>;
{{- end}}
{{- if .ReturnsEmpty}}
  {{.lowerName}}(input: {{.InputTypeName}}): Promise<void>;
{{- end}}
{{- end}}
}
