// Code generated by mss-protoc-gen. DO NOT EDIT.

package entity

import (
	"errors"
	"strings"
	"time"
)

type {{.Name}} struct {
{{- range .Fields}}
	{{.GoName}} {{.GoType}}
{{- end}}
}

func New{{.Name}}(
{{- range .Fields}}
	{{.ParamName}} {{.GoType}},
{{- end}}
) (*{{.Name}}, error) {
{{- range .Fields}}
{{- if .IsPK}}
	if {{.ParamName}} == "" {
		return nil, errors.New("{{.SnakeName}} is required")
	}
{{- end}}
{{- if and .IsRequired (eq .GoType "string")}}
	{{.ParamName}} = strings.TrimSpace({{.ParamName}})
	if {{.ParamName}} == "" {
		return nil, errors.New("{{.SnakeName}} is required")
	}
{{- end}}
{{- if .IsEmail}}
	{{.ParamName}} = strings.TrimSpace({{.ParamName}})
	if {{.ParamName}} == "" || !strings.Contains({{.ParamName}}, "@") {
		return nil, errors.New("{{.SnakeName}} is invalid")
	}
{{- end}}
{{- end}}
	return &{{.Name}}{
{{- range .Fields}}
		{{.GoName}}: {{.ParamName}},
{{- end}}
	}, nil
}

// Hydrate{{.Name}} は永続化層から復元した値で {{.Name}} を組み立てる。
// バリデーションは走らない。通常コードパスでは New{{.Name}} を使うこと。
func Hydrate{{.Name}}(
{{- range .Fields}}
	{{.ParamName}} {{.GoType}},
{{- end}}
) *{{.Name}} {
	return &{{.Name}}{
{{- range .Fields}}
		{{.GoName}}: {{.ParamName}},
{{- end}}
	}
}

var _ = time.Time{}
