// Code generated by mss-protoc-gen. DO NOT EDIT.

import type { User } from "../domain/entity/user.gen.js";

/**
 * UserDTO は User エンティティをクライアントへ返すための JSON シリアライズ型。
 * snake_case のキーで wire format を表す。entity 側は ORM タグ + バリデーションのみを持ち、
 * クライアント返却型は DTO 層で一元管理する。
 */
export type UserDTO = {
  id: string;
  email: string;
  name: string;
  created_at_unix: number;
};

export function fromUser(e: User): UserDTO {
  return {
    id: e.id,
    email: e.email,
    name: e.name,
    created_at_unix: Math.floor(e.createdAt.getTime() / 1000),
  };
}

export function fromUsers(es: User[]): UserDTO[] {
  return es.map(fromUser);
}
