# Code generated by mss-protoc-gen. DO NOT EDIT.
from __future__ import annotations
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from app.usecase.user_usecase_interface import (
    ListUsersInput,
    ListUsersByCursorInput,
    GetUserByEmailInput,
    GetUserInput,
    CreateUserInput,
    BulkCreateUsersInput,
    BulkUpsertUsersInput,
    UpsertUserInput,
    UpdateUserInput,
    BulkDeleteUsersInput,
    DeleteUserInput,
    DeleteAllUsersInput,
    CreateUserParams,
    UpsertUserParams,
    UserServiceUsecase,
)
from app.domain.repository.user_repository import (
    UserNotFoundError,
    UserAlreadyExistsError,
)

class CreateUserBody(BaseModel):
    email: str
    name: str


class BulkCreateUsersBody(BaseModel):
    users: list[CreateUserParams]


class BulkUpsertUsersBody(BaseModel):
    users: list[UpsertUserParams]


class UpsertUserBody(BaseModel):
    email: str
    name: str
    created_at_unix: int


class UpdateUserBody(BaseModel):
    email: str
    name: str


class BulkDeleteUsersBody(BaseModel):
    ids: list[str]


def new_user_router(uc: UserServiceUsecase) -> APIRouter:
    router = APIRouter()

    @router.get("/api/users")
    def list_users(
    ):
        try:
            result = uc.list_users(
                ListUsersInput(
                )
            )
        except UserNotFoundError:
            raise HTTPException(status_code=404, detail="not found")
        except UserAlreadyExistsError:
            raise HTTPException(status_code=409, detail="already exists")
        except ValueError as ex:
            raise HTTPException(status_code=400, detail=str(ex))
        return [d.to_dict() for d in result]

    @router.get("/api/users/cursor")
    def list_users_by_cursor(
        limit: int | None = None,
        after_id: str | None = None,
    ):
        try:
            result = uc.list_users_by_cursor(
                ListUsersByCursorInput(
                    limit=limit,
                    after_id=after_id,
                )
            )
        except UserNotFoundError:
            raise HTTPException(status_code=404, detail="not found")
        except UserAlreadyExistsError:
            raise HTTPException(status_code=409, detail="already exists")
        except ValueError as ex:
            raise HTTPException(status_code=400, detail=str(ex))
        return [d.to_dict() for d in result]

    @router.get("/api/users/by-email")
    def get_user_by_email(
        email: str | None = None,
    ):
        try:
            result = uc.get_user_by_email(
                GetUserByEmailInput(
                    email=email,
                )
            )
        except UserNotFoundError:
            raise HTTPException(status_code=404, detail="not found")
        except UserAlreadyExistsError:
            raise HTTPException(status_code=409, detail="already exists")
        except ValueError as ex:
            raise HTTPException(status_code=400, detail=str(ex))
        if result is None:
            raise HTTPException(status_code=404, detail="not found")
        return result.to_dict()

    @router.get("/api/users/{id}")
    def get_user(
        id: str,
    ):
        try:
            result = uc.get_user(
                GetUserInput(
                    id=id,
                )
            )
        except UserNotFoundError:
            raise HTTPException(status_code=404, detail="not found")
        except UserAlreadyExistsError:
            raise HTTPException(status_code=409, detail="already exists")
        except ValueError as ex:
            raise HTTPException(status_code=400, detail=str(ex))
        if result is None:
            raise HTTPException(status_code=404, detail="not found")
        return result.to_dict()

    @router.post("/api/users", status_code=201)
    def create_user(
        body: CreateUserBody,
    ):
        try:
            result = uc.create_user(
                CreateUserInput(
                    email=body.email,
                    name=body.name,
                )
            )
        except UserNotFoundError:
            raise HTTPException(status_code=404, detail="not found")
        except UserAlreadyExistsError:
            raise HTTPException(status_code=409, detail="already exists")
        except ValueError as ex:
            raise HTTPException(status_code=400, detail=str(ex))
        if result is None:
            raise HTTPException(status_code=404, detail="not found")
        return result.to_dict()

    @router.post("/api/users/bulk", status_code=201)
    def bulk_create_users(
        body: BulkCreateUsersBody,
    ):
        try:
            result = uc.bulk_create_users(
                BulkCreateUsersInput(
                    users=body.users,
                )
            )
        except UserNotFoundError:
            raise HTTPException(status_code=404, detail="not found")
        except UserAlreadyExistsError:
            raise HTTPException(status_code=409, detail="already exists")
        except ValueError as ex:
            raise HTTPException(status_code=400, detail=str(ex))
        return [d.to_dict() for d in result]

    @router.put("/api/users/bulk")
    def bulk_upsert_users(
        body: BulkUpsertUsersBody,
    ):
        try:
            result = uc.bulk_upsert_users(
                BulkUpsertUsersInput(
                    users=body.users,
                )
            )
        except UserNotFoundError:
            raise HTTPException(status_code=404, detail="not found")
        except UserAlreadyExistsError:
            raise HTTPException(status_code=409, detail="already exists")
        except ValueError as ex:
            raise HTTPException(status_code=400, detail=str(ex))
        return [d.to_dict() for d in result]

    @router.put("/api/users/{id}")
    def upsert_user(
        id: str,
        body: UpsertUserBody,
    ):
        try:
            result = uc.upsert_user(
                UpsertUserInput(
                    id=id,
                    email=body.email,
                    name=body.name,
                    created_at_unix=body.created_at_unix,
                )
            )
        except UserNotFoundError:
            raise HTTPException(status_code=404, detail="not found")
        except UserAlreadyExistsError:
            raise HTTPException(status_code=409, detail="already exists")
        except ValueError as ex:
            raise HTTPException(status_code=400, detail=str(ex))
        if result is None:
            raise HTTPException(status_code=404, detail="not found")
        return result.to_dict()

    @router.patch("/api/users/{id}")
    def update_user(
        id: str,
        body: UpdateUserBody,
    ):
        try:
            result = uc.update_user(
                UpdateUserInput(
                    id=id,
                    email=body.email,
                    name=body.name,
                )
            )
        except UserNotFoundError:
            raise HTTPException(status_code=404, detail="not found")
        except UserAlreadyExistsError:
            raise HTTPException(status_code=409, detail="already exists")
        except ValueError as ex:
            raise HTTPException(status_code=400, detail=str(ex))
        if result is None:
            raise HTTPException(status_code=404, detail="not found")
        return result.to_dict()

    @router.post("/api/users/bulk-delete", status_code=201)
    def bulk_delete_users(
        body: BulkDeleteUsersBody,
    ):
        try:
            uc.bulk_delete_users(
                BulkDeleteUsersInput(
                    ids=body.ids,
                )
            )
        except UserNotFoundError:
            raise HTTPException(status_code=404, detail="not found")
        except UserAlreadyExistsError:
            raise HTTPException(status_code=409, detail="already exists")
        except ValueError as ex:
            raise HTTPException(status_code=400, detail=str(ex))
        return None

    @router.delete("/api/users/{id}", status_code=204)
    def delete_user(
        id: str,
    ):
        try:
            uc.delete_user(
                DeleteUserInput(
                    id=id,
                )
            )
        except UserNotFoundError:
            raise HTTPException(status_code=404, detail="not found")
        except UserAlreadyExistsError:
            raise HTTPException(status_code=409, detail="already exists")
        except ValueError as ex:
            raise HTTPException(status_code=400, detail=str(ex))
        return None

    @router.delete("/api/users", status_code=204)
    def delete_all_users(
    ):
        try:
            uc.delete_all_users(
                DeleteAllUsersInput(
                )
            )
        except UserNotFoundError:
            raise HTTPException(status_code=404, detail="not found")
        except UserAlreadyExistsError:
            raise HTTPException(status_code=409, detail="already exists")
        except ValueError as ex:
            raise HTTPException(status_code=400, detail=str(ex))
        return None
    return router
