// Code generated by mss-protoc-gen. DO NOT EDIT.

package handler

import (
	"encoding/json"
	"errors"
	"net/http"

	"github.com/example/manji-standard-server-go/pkg/domain/entity"
	"github.com/example/manji-standard-server-go/pkg/domain/repository"
	"github.com/example/manji-standard-server-go/pkg/usecase"
)

type UserHandler struct {
	usecase usecase.UserUsecase
}

func NewUserHandler(uc usecase.UserUsecase) *UserHandler {
	return &UserHandler{usecase: uc}
}

func userToJSON(e *entity.User) map[string]any {
	if e == nil {
		return nil
	}
	return map[string]any{
		"id":              e.ID,
		"email":           e.Email,
		"name":            e.Name,
		"created_at_unix": e.CreatedAt.Unix(),
	}
}

func (h *UserHandler) writeError(w http.ResponseWriter, err error) {
	status := http.StatusBadRequest
	if errors.Is(err, repository.ErrUserNotFound) {
		status = http.StatusNotFound
	}
	if errors.Is(err, repository.ErrUserAlreadyExists) {
		status = http.StatusConflict
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(map[string]string{"error": err.Error()})
}

type CreateUserBody struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

// POST /api/users
func (h *UserHandler) CreateUser(w http.ResponseWriter, r *http.Request) {
	var body CreateUserBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		_ = json.NewEncoder(w).Encode(map[string]string{"error": "invalid body"})
		return
	}
	result, err := h.usecase.CreateUser(r.Context(), usecase.CreateUserInput{
		Email: body.Email,
		Name:  body.Name,
	})
	if err != nil {
		h.writeError(w, err)
		return
	}
	if result == nil {
		h.writeError(w, repository.ErrUserNotFound)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_ = json.NewEncoder(w).Encode(userToJSON(result))
}

// GET /api/users/{id}
func (h *UserHandler) GetUser(w http.ResponseWriter, r *http.Request) {
	result, err := h.usecase.GetUser(r.Context(), usecase.GetUserInput{
		ID: r.PathValue("id"),
	})
	if err != nil {
		h.writeError(w, err)
		return
	}
	if result == nil {
		h.writeError(w, repository.ErrUserNotFound)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_ = json.NewEncoder(w).Encode(userToJSON(result))
}
