// Code generated by mss-protoc-gen. DO NOT EDIT.

package entity

import (
	"errors"
	"strings"
	"time"
)

type User struct {
	ID        string    `gorm:"column:id;primaryKey"`
	Email     string    `gorm:"column:email;uniqueIndex;not null"`
	Name      string    `gorm:"column:name;not null"`
	CreatedAt time.Time `gorm:"column:created_at;not null"`
}

func (User) TableName() string { return "users" }

func NewUser(
	id string,
	email string,
	name string,
	createdAt time.Time,
) (*User, error) {
	if id == "" {
		return nil, errors.New("id is required")
	}
	email = strings.TrimSpace(email)
	if email == "" || !strings.Contains(email, "@") {
		return nil, errors.New("email is invalid")
	}
	name = strings.TrimSpace(name)
	if name == "" {
		return nil, errors.New("name is required")
	}
	return &User{
		ID:        id,
		Email:     email,
		Name:      name,
		CreatedAt: createdAt,
	}, nil
}

var _ = time.Time{}
