// Code generated by mss-protoc-gen. DO NOT EDIT.

import "@/lib/container"; // side-effect: HandlerDeps factory を登録
import { NextResponse } from "next/server";


import {
  UserNotFoundError,
  UserAlreadyExistsError,
} from "@/domain/repository/user-repository.gen";
import { getHandlerDeps } from "@/lib/handler-registry.gen";
import type {
  UserUsecase,
  BulkCreateUsersInput,
  BulkUpsertUsersInput,
  CreateUserParams,
  UpsertUserParams,
} from "@/usecase/user-usecase-interface.gen";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function toHttpError(err: unknown): NextResponse {
  if (err instanceof UserNotFoundError) return NextResponse.json({ error: err.message }, { status: 404 });
  if (err instanceof UserAlreadyExistsError) return NextResponse.json({ error: err.message }, { status: 409 });
  const message = err instanceof Error ? err.message : "unknown error";
  return NextResponse.json({ error: message }, { status: 400 });
}


type BulkCreateUsersBody = {
  users?: CreateUserParams[];
};
export async function POST(
  req: Request,
) {
  let body: BulkCreateUsersBody;
  try {
    body = (await req.json()) as BulkCreateUsersBody;
  } catch {
    return NextResponse.json({ error: "invalid body" }, { status: 400 });
  }
  try {
    const deps = getHandlerDeps();
    const input: BulkCreateUsersInput = {
      users: (body.users ?? []) as CreateUserParams[],
    };
    const list = await deps.userUsecase.bulkCreateUsers(input);
    return NextResponse.json(list, { status: 201 });
  } catch (err) {
    return toHttpError(err);
  }
}

type BulkUpsertUsersBody = {
  users?: UpsertUserParams[];
};
export async function PUT(
  req: Request,
) {
  let body: BulkUpsertUsersBody;
  try {
    body = (await req.json()) as BulkUpsertUsersBody;
  } catch {
    return NextResponse.json({ error: "invalid body" }, { status: 400 });
  }
  try {
    const deps = getHandlerDeps();
    const input: BulkUpsertUsersInput = {
      users: (body.users ?? []) as UpsertUserParams[],
    };
    const list = await deps.userUsecase.bulkUpsertUsers(input);
    return NextResponse.json(list, { status: 200 });
  } catch (err) {
    return toHttpError(err);
  }
}
