// Code generated by mss-protoc-gen. DO NOT EDIT.

import { vi } from "vitest";
import type { {{.Name}} } from "../../entity/{{.Kebab}}.gen.js";
import type { {{.Name}}Repository } from "../{{.Kebab}}-repository.gen.js";

export class Mock{{.Name}}Repository implements {{.Name}}Repository {
  selectAll = vi.fn<() => Promise<{{.Name}}[]>>(async () => []);
  selectByPk = vi.fn<({{.PKField.name}}: {{.PKField.type}}) => Promise<{{.Name}} | null>>(async () => null);
{{- range .UniqueFieldsNonPK}}
  selectBy{{capitalize .name}} = vi.fn<({{.name}}: {{.type}}) => Promise<{{$.Name}} | null>>(async () => null);
{{- end}}
  insert = vi.fn<({{.LowerFirst}}: {{.Name}}) => Promise<void>>(async () => {});
  bulkInsert = vi.fn<({{.Plural}}: {{.Name}}[]) => Promise<void>>(async () => {});
  upsert = vi.fn<({{.LowerFirst}}: {{.Name}}) => Promise<void>>(async () => {});
  bulkUpsert = vi.fn<({{.Plural}}: {{.Name}}[]) => Promise<void>>(async () => {});
  update = vi.fn<({{.LowerFirst}}: {{.Name}}) => Promise<void>>(async () => {});
  delete = vi.fn<({{.PKField.name}}: {{.PKField.type}}) => Promise<void>>(async () => {});
  bulkDelete = vi.fn<({{.PKField.name}}s: {{.PKField.type}}[]) => Promise<void>>(async () => {});
  deleteAll = vi.fn<() => Promise<void>>(async () => {});
}
