// Code generated by mss-protoc-gen. DO NOT EDIT.

import "@/lib/container"; // side-effect: HandlerDeps factory を登録
import { NextResponse } from "next/server";


import { getHandlerDeps } from "@/lib/handler-registry.gen";
import type {
  UserUsecase,
  BulkDeleteUsersInput,
  CreateUserParams,
  UpsertUserParams,
} from "@/usecase/user-usecase-interface.gen";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function toHttpError(err: unknown): NextResponse {
  const message = err instanceof Error ? err.message : "unknown error";
  return NextResponse.json({ error: message }, { status: 400 });
}


type BulkDeleteUsersBody = {
  ids?: string[];
};
export async function POST(
  req: Request,
) {
  let body: BulkDeleteUsersBody;
  try {
    body = (await req.json()) as BulkDeleteUsersBody;
  } catch {
    return NextResponse.json({ error: "invalid body" }, { status: 400 });
  }
  try {
    const deps = getHandlerDeps();
    const input: BulkDeleteUsersInput = {
      ids: (body.ids ?? []) as string[],
    };
    await deps.userUsecase.bulkDeleteUsers(input);
    return new NextResponse(null, { status: 204 });
  } catch (err) {
    return toHttpError(err);
  }
}
