# Code generated by mss-protoc-gen. DO NOT EDIT.
from __future__ import annotations
from collections.abc import Callable
from app.domain.entity.user import User


class MockUserRepository:
    """テスト用 mock。各 *_func を差し替えて振る舞いを注入する(Go の func フィールド相当)。"""

    def __init__(self) -> None:
        self.select_all_func: Callable | None = None
        self.select_by_pk_func: Callable | None = None
        self.select_by_email_func: Callable | None = None
        self.insert_func: Callable | None = None
        self.bulk_insert_func: Callable | None = None
        self.upsert_func: Callable | None = None
        self.bulk_upsert_func: Callable | None = None
        self.update_func: Callable | None = None
        self.delete_func: Callable | None = None
        self.bulk_delete_func: Callable | None = None
        self.delete_all_func: Callable | None = None
        self.select_by_cursor_func: Callable | None = None

    def select_all(self) -> list[User]:
        return self.select_all_func() if self.select_all_func else []

    def select_by_pk(self, id) -> User | None:
        return self.select_by_pk_func(id) if self.select_by_pk_func else None

    def select_by_email(self, email) -> User | None:
        return self.select_by_email_func(email) if self.select_by_email_func else None

    def insert(self, e) -> None:
        if self.insert_func:
            self.insert_func(e)

    def bulk_insert(self, es) -> None:
        if self.bulk_insert_func:
            self.bulk_insert_func(es)

    def upsert(self, e) -> None:
        if self.upsert_func:
            self.upsert_func(e)

    def bulk_upsert(self, es) -> None:
        if self.bulk_upsert_func:
            self.bulk_upsert_func(es)

    def update(self, e) -> None:
        if self.update_func:
            self.update_func(e)

    def delete(self, id) -> None:
        if self.delete_func:
            self.delete_func(id)

    def bulk_delete(self, ids) -> None:
        if self.bulk_delete_func:
            self.bulk_delete_func(ids)

    def delete_all(self) -> None:
        if self.delete_all_func:
            self.delete_all_func()

    def select_by_cursor(self, limit, after) -> list[User]:
        return self.select_by_cursor_func(limit, after) if self.select_by_cursor_func else []
