// Code generated by mss-protoc-gen. DO NOT EDIT.

{{range .Services}}
import type { {{.UsecaseTypeName}} } from "@/usecase/{{.Kebab}}-usecase-interface.gen";
{{- end}}

// REST Route Handler が使う依存一覧。container 側で factory を登録する。
export type HandlerDeps = {
{{- range .Services}}
  {{.UsecaseVarName}}: {{.UsecaseTypeName}};
{{- end}}
};

let _deps: HandlerDeps | undefined;
let _factory: (() => HandlerDeps) | undefined;

/**
 * 起動時（container.ts の module load 時）に呼び、実際の初期化は遅延させる。
 * これにより Next.js の build 時の Route Handler メタデータ収集で DB 接続を行わない。
 */
export function provideHandlerDepsFactory(factory: () => HandlerDeps): void {
  _factory = factory;
}

/** 生成された Route Handler から request 時に呼ばれる。初回で factory を実行して確定させる。 */
export function getHandlerDeps(): HandlerDeps {
  if (_deps) return _deps;
  if (!_factory) {
    throw new Error("HandlerDeps factory not provided. Import '@/lib/container' from Route Handlers.");
  }
  _deps = _factory();
  return _deps;
}
