// Code generated by mss-protoc-gen. DO NOT EDIT.

import { UserForm } from "../../../../gen/ui/user/UserForm";

export default function EditUserPage({ params }: { params: { id: string } }) {
  return (<main style={{ maxWidth: 640, margin: "2rem auto", fontFamily: "system-ui" }}><h1>Edit User</h1><UserForm id={params.id} /></main>);
}
