// Code generated by mss-protoc-gen. DO NOT EDIT.

import { UserForm } from "../../../../gen/ui/user/UserForm";
import { Page } from "../../../../lib/widgets";

export default function EditUserPage({ params }: { params: { id: string } }) {
  return (<Page title="Edit User"><UserForm id={params.id} /></Page>);
}
