// Code generated by mss-protoc-gen. DO NOT EDIT.

package repository

import (
	"context"
	"errors"
	"time"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"

	"github.com/example/manji-standard-server-go/internal/domain/entity"
	"github.com/example/manji-standard-server-go/internal/domain/repository"
	"github.com/example/manji-standard-server-go/pkg/util/tx"
)

type postgresUserRepository struct{}

func NewPostgresUserRepository() repository.UserRepository {
	return &postgresUserRepository{}
}

// AutoMigrateUser は開発用途のスキーマ同期ヘルパー。
// 本番では Goose / Atlas / Flyway 等のマイグレーションツールを使うこと。
func AutoMigrateUser(db *gorm.DB) error {
	return db.AutoMigrate(&entity.User{})
}

var _ repository.UserRepository = (*postgresUserRepository)(nil)
var _ = time.Time{}

func (r *postgresUserRepository) SelectAll(ctx context.Context) ([]*entity.User, error) {
	var out []*entity.User
	if err := tx.From(ctx).WithContext(ctx).Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}

func (r *postgresUserRepository) SelectByPK(ctx context.Context, id string) (*entity.User, error) {
	var e entity.User
	err := tx.From(ctx).WithContext(ctx).Where("id = ?", id).First(&e).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return &e, nil
}

func (r *postgresUserRepository) SelectByEmail(ctx context.Context, email string) (*entity.User, error) {
	var e entity.User
	err := tx.From(ctx).WithContext(ctx).Where("email = ?", email).First(&e).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return &e, nil
}

func (r *postgresUserRepository) Insert(ctx context.Context, user *entity.User) error {
	if err := tx.From(ctx).WithContext(ctx).Create(user).Error; err != nil {
		if errors.Is(err, gorm.ErrDuplicatedKey) {
			return repository.ErrUserAlreadyExists
		}
		return err
	}
	return nil
}

func (r *postgresUserRepository) BulkInsert(ctx context.Context, users []*entity.User) error {
	if len(users) == 0 {
		return nil
	}
	if err := tx.From(ctx).WithContext(ctx).CreateInBatches(users, 100).Error; err != nil {
		if errors.Is(err, gorm.ErrDuplicatedKey) {
			return repository.ErrUserAlreadyExists
		}
		return err
	}
	return nil
}

func (r *postgresUserRepository) Upsert(ctx context.Context, user *entity.User) error {
	return tx.From(ctx).WithContext(ctx).Clauses(clause.OnConflict{UpdateAll: true}).Create(user).Error
}

func (r *postgresUserRepository) BulkUpsert(ctx context.Context, users []*entity.User) error {
	if len(users) == 0 {
		return nil
	}
	return tx.From(ctx).WithContext(ctx).Clauses(clause.OnConflict{UpdateAll: true}).CreateInBatches(users, 100).Error
}

func (r *postgresUserRepository) Update(ctx context.Context, user *entity.User) error {
	res := tx.From(ctx).WithContext(ctx).Model(&entity.User{}).Where("id = ?", user.ID).Updates(user)
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return repository.ErrUserNotFound
	}
	return nil
}

func (r *postgresUserRepository) Delete(ctx context.Context, id string) error {
	res := tx.From(ctx).WithContext(ctx).Where("id = ?", id).Delete(&entity.User{})
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return repository.ErrUserNotFound
	}
	return nil
}

func (r *postgresUserRepository) BulkDelete(ctx context.Context, ids []string) error {
	if len(ids) == 0 {
		return nil
	}
	res := tx.From(ctx).WithContext(ctx).Where("id IN ?", ids).Delete(&entity.User{})
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected != int64(len(ids)) {
		return repository.ErrUserNotFound
	}
	return nil
}

func (r *postgresUserRepository) DeleteAll(ctx context.Context) error {
	return tx.From(ctx).WithContext(ctx).Where("1 = 1").Delete(&entity.User{}).Error
}

func (r *postgresUserRepository) SelectByCursor(ctx context.Context, limit int, after *string) ([]*entity.User, error) {
	q := tx.From(ctx).WithContext(ctx).Order("id ASC").Limit(limit)
	if after != nil {
		q = q.Where("id > ?", *after)
	}
	var out []*entity.User
	if err := q.Find(&out).Error; err != nil {
		return nil, err
	}
	return out, nil
}
