// Code generated by mss-protoc-gen. DO NOT EDIT.

import { asc, eq, gt, inArray } from "drizzle-orm";
import type { NodePgDatabase } from "drizzle-orm/node-postgres";

import { User, usersTable, type UserInsert } from "../../domain/entity/user.gen";
import {
  type UserRepository,
  UserNotFoundError,
  UserAlreadyExistsError,
} from "../../domain/repository/user-repository.gen";

function rowToUser(r: typeof usersTable.$inferSelect): User {
  return User.hydrate({
    id: r.id,
    email: r.email,
    name: r.name,
    createdAt: r.createdAt,
  });
}

function userToRow(user: User): UserInsert {
  return {
    id: user.id,
    email: user.email,
    name: user.name,
    createdAt: user.createdAt,
  };
}

function isUniqueViolation(err: unknown): boolean {
  return typeof err === "object" && err !== null && (err as { code?: string }).code === "23505";
}

export class PostgresUserRepository implements UserRepository {
  constructor(private readonly db: NodePgDatabase<Record<string, never>>) {}

  async selectAll(): Promise<User[]> {
    const rows = await this.db.select().from(usersTable);
    return rows.map(rowToUser);
  }

  async selectByPk(id: string): Promise<User | null> {
    const rows = await this.db.select().from(usersTable).where(eq(usersTable.id, id)).limit(1);
    return rows[0] ? rowToUser(rows[0]) : null;
  }

  async selectByEmail(email: string): Promise<User | null> {
    const rows = await this.db.select().from(usersTable).where(eq(usersTable.email, email)).limit(1);
    return rows[0] ? rowToUser(rows[0]) : null;
  }

  async insert(user: User): Promise<void> {
    try {
      await this.db.insert(usersTable).values(userToRow(user));
    } catch (e) {
      if (isUniqueViolation(e)) throw new UserAlreadyExistsError();
      throw e;
    }
  }

  async bulkInsert(users: User[]): Promise<void> {
    if (users.length === 0) return;
    await this.db.transaction(async (tx) => {
      try {
        await tx.insert(usersTable).values(users.map(userToRow));
      } catch (e) {
        if (isUniqueViolation(e)) throw new UserAlreadyExistsError();
        throw e;
      }
    });
  }

  async upsert(user: User): Promise<void> {
    const row = userToRow(user);
    await this.db.insert(usersTable).values(row).onConflictDoUpdate({
      target: usersTable.id,
      set: row,
    });
  }

  async bulkUpsert(users: User[]): Promise<void> {
    if (users.length === 0) return;
    await this.db.transaction(async (tx) => {
      for (const user of users) {
        const row = userToRow(user);
        await tx.insert(usersTable).values(row).onConflictDoUpdate({
          target: usersTable.id,
          set: row,
        });
      }
    });
  }

  async update(user: User): Promise<void> {
    const row = userToRow(user);
    const res = await this.db.update(usersTable).set(row).where(eq(usersTable.id, user.id));
    if ((res as { rowCount?: number | null }).rowCount === 0) throw new UserNotFoundError();
  }

  async delete(id: string): Promise<void> {
    const res = await this.db.delete(usersTable).where(eq(usersTable.id, id));
    if ((res as { rowCount?: number | null }).rowCount === 0) throw new UserNotFoundError();
  }

  async bulkDelete(ids: string[]): Promise<void> {
    if (ids.length === 0) return;
    await this.db.transaction(async (tx) => {
      const res = await tx.delete(usersTable).where(inArray(usersTable.id, ids));
      if ((res as { rowCount?: number | null }).rowCount !== ids.length) throw new UserNotFoundError();
    });
  }

  async deleteAll(): Promise<void> {
    await this.db.delete(usersTable);
  }

  async selectByCursor(limit: number, after: string | null): Promise<User[]> {
    const q = this.db.select().from(usersTable).orderBy(asc(usersTable.id)).limit(limit);
    const rows = after === null
      ? await q
      : await q.where(gt(usersTable.id, after));
    return rows.map(rowToUser);
  }
}
