// Code generated by mss-protoc-gen. DO NOT EDIT.

import "@/lib/container"; // side-effect: HandlerDeps factory を登録
import { NextResponse } from "next/server";

{{range .UsedEntities}}
import {
  {{.Name}}NotFoundError,
  {{.Name}}AlreadyExistsError,
} from "@/domain/repository/{{.Kebab}}-repository.gen";
{{- end}}
import { getHandlerDeps } from "@/lib/handler-registry.gen";
import type {
  {{.UsecaseTypeName}},
{{- range .Methods}}
  {{.InputTypeName}},
{{- end}}
{{- range .NonEntityTypes}}
  {{.Name}},
{{- end}}
} from "@/usecase/{{.Kebab}}-usecase-interface.gen";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function toHttpError(err: unknown): NextResponse {
{{- range .UsedEntities}}
  if (err instanceof {{.Name}}NotFoundError) return NextResponse.json({ error: err.message }, { status: 404 });
  if (err instanceof {{.Name}}AlreadyExistsError) return NextResponse.json({ error: err.message }, { status: 409 });
{{- end}}
  const message = err instanceof Error ? err.message : "unknown error";
  return NextResponse.json({ error: message }, { status: 400 });
}

{{range .Methods}}
{{- if and .IsBodyMethod .HasBodyFields}}
type {{.rpcName}}Body = {
{{- range .BodyFields}}
  {{.jsonName}}?: {{.type}};
{{- end}}
};
{{- end}}

{{- if or (and .IsBodyMethod .HasBodyFields) .HasQueryFields}}
export async function {{.Http.Method}}(
  req: Request,
{{- else}}
export async function {{.Http.Method}}(
  _req: Request,
{{- end}}
{{- if .HasPathParams}}
  { params }: { params: { {{range .PathParamFields}}{{.jsonName}}: string; {{end}}} },
{{- end}}
) {
{{- if and .IsBodyMethod .HasBodyFields}}
  let body: {{.rpcName}}Body;
  try {
    body = (await req.json()) as {{.rpcName}}Body;
  } catch {
    return NextResponse.json({ error: "invalid body" }, { status: 400 });
  }
{{- end}}
{{- if .HasQueryFields}}
  const searchParams = new URL(req.url).searchParams;
{{- end}}
  try {
    const deps = getHandlerDeps();
{{- if .HasInputFields}}
    const input: {{.InputTypeName}} = {
{{- range .InputFields}}
      {{.name}}: {{.assignExpr}},
{{- end}}
    };
{{- else}}
    const input = {} as {{.InputTypeName}};
{{- end}}
{{- if .ReturnsEntity}}
    const result = await deps.{{.UsecaseVarName}}.{{.lowerName}}(input);
    if (!result) return NextResponse.json({ error: "{{.EntityLowerFirst}} not found" }, { status: 404 });
    return NextResponse.json(result, { status: {{if eq .Http.Method "POST"}}201{{else}}200{{end}} });
{{- end}}
{{- if .ReturnsList}}
    const list = await deps.{{.UsecaseVarName}}.{{.lowerName}}(input);
    return NextResponse.json(list, { status: {{if eq .Http.Method "POST"}}201{{else}}200{{end}} });
{{- end}}
{{- if .ReturnsEmpty}}
    await deps.{{.UsecaseVarName}}.{{.lowerName}}(input);
    return new NextResponse(null, { status: 204 });
{{- end}}
  } catch (err) {
    return toHttpError(err);
  }
}
{{end}}
