// Code generated by mss-protoc-gen. DO NOT EDIT.

import "@/lib/container"; // side-effect: HandlerDeps factory を登録
import { NextResponse } from "next/server";

{{range .UsedEntities}}
import type { {{.Name}} } from "@/domain/entity/{{.Kebab}}.gen";
import {
  {{.Name}}NotFoundError,
  {{.Name}}AlreadyExistsError,
} from "@/domain/repository/{{.Kebab}}-repository.gen";
{{- end}}
import { getHandlerDeps } from "@/lib/handler-registry.gen";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

{{range .UsedEntities}}
function {{.LowerFirst}}ToJson(e: {{.Name}}) {
  return {
{{- range .Fields}}
{{- if .isTimestamp}}
    {{.name}}Unix: Math.floor(e.{{.name}}.getTime() / 1000),
{{- else}}
    {{.name}}: e.{{.name}},
{{- end}}
{{- end}}
  };
}
{{end}}
function toHttpError(err: unknown): NextResponse {
{{- range .UsedEntities}}
  if (err instanceof {{.Name}}NotFoundError) return NextResponse.json({ error: err.message }, { status: 404 });
  if (err instanceof {{.Name}}AlreadyExistsError) return NextResponse.json({ error: err.message }, { status: 409 });
{{- end}}
  const message = err instanceof Error ? err.message : "unknown error";
  return NextResponse.json({ error: message }, { status: 400 });
}

{{range .Methods}}
{{- if .HasBodyFields}}
type {{.rpcName}}Body = {
{{- range .BodyFields}}
  {{.name}}?: {{.type}};
{{- end}}
};
{{- end}}

export async function {{.Http.Method}}(
{{- if .HasBodyFields}}
  req: Request,
{{- end}}
{{- if .HasPathParams}}
{{- if .HasBodyFields}}{{else}}
  _req: Request,
{{- end}}
  { params }: { params: { {{range .PathParamFields}}{{.name}}: {{.type}}; {{end}}} },
{{- end}}
{{- if .HasBodyFields}}{{else}}{{if .HasPathParams}}{{else}}
  _req: Request,
{{- end}}{{end}}
) {
{{- if .HasBodyFields}}
  let body: {{.rpcName}}Body;
  try {
    body = (await req.json()) as {{.rpcName}}Body;
  } catch {
    return NextResponse.json({ error: "invalid body" }, { status: 400 });
  }
{{- end}}
  try {
    const deps = getHandlerDeps();
{{- if .ReturnsEntity}}
    const e = await deps.{{.UsecaseVarName}}.{{.lowerName}}({
{{- range .PathParamFields}}
      {{.name}}: params.{{.name}},
{{- end}}
{{- range .BodyFields}}
{{- if eq .type "string"}}
      {{.name}}: body.{{.name}} ?? "",
{{- end}}
{{- if eq .type "number"}}
      {{.name}}: body.{{.name}} ?? 0,
{{- end}}
{{- if eq .type "boolean"}}
      {{.name}}: body.{{.name}} ?? false,
{{- end}}
{{- end}}
    });
    if (!e) return NextResponse.json({ error: "{{.EntityLowerFirst}} not found" }, { status: 404 });
    return NextResponse.json({{.EntityLowerFirst}}ToJson(e), { status: {{if eq .Http.Method "POST"}}201{{else}}200{{end}} });
{{- end}}
{{- if .ReturnsList}}
    const list = await deps.{{.UsecaseVarName}}.{{.lowerName}}({
{{- range .PathParamFields}}
      {{.name}}: params.{{.name}},
{{- end}}
{{- range .BodyFields}}
{{- if eq .type "string"}}
      {{.name}}: body.{{.name}} ?? "",
{{- end}}
{{- if eq .type "number"}}
      {{.name}}: body.{{.name}} ?? 0,
{{- end}}
{{- if eq .type "boolean"}}
      {{.name}}: body.{{.name}} ?? false,
{{- end}}
{{- end}}
    });
    return NextResponse.json(list.map({{.EntityLowerFirst}}ToJson), { status: 200 });
{{- end}}
{{- if .ReturnsEmpty}}
    await deps.{{.UsecaseVarName}}.{{.lowerName}}({
{{- range .PathParamFields}}
      {{.name}}: params.{{.name}},
{{- end}}
{{- range .BodyFields}}
{{- if eq .type "string"}}
      {{.name}}: body.{{.name}} ?? "",
{{- end}}
{{- if eq .type "number"}}
      {{.name}}: body.{{.name}} ?? 0,
{{- end}}
{{- if eq .type "boolean"}}
      {{.name}}: body.{{.name}} ?? false,
{{- end}}
{{- end}}
    });
    return new NextResponse(null, { status: 204 });
{{- end}}
  } catch (err) {
    return toHttpError(err);
  }
}
{{end}}
