// Code generated by mss-protoc-gen. DO NOT EDIT.

import type { User } from "../entity/user.gen.js";

export class UserNotFoundError extends Error {
  constructor() {
    super("user not found");
    this.name = "UserNotFoundError";
  }
}

export class UserAlreadyExistsError extends Error {
  constructor() {
    super("user already exists");
    this.name = "UserAlreadyExistsError";
  }
}

export interface UserRepository {
  selectAll(): Promise<User[]>;
  selectByPk(id: string): Promise<User | null>;
  selectByEmail(email: string): Promise<User | null>;
  insert(user: User): Promise<void>;
  bulkInsert(users: User[]): Promise<void>;
  upsert(user: User): Promise<void>;
  bulkUpsert(users: User[]): Promise<void>;
  update(user: User): Promise<void>;
  delete(id: string): Promise<void>;
  bulkDelete(ids: string[]): Promise<void>;
  deleteAll(): Promise<void>;
}
