# Code generated by mss-protoc-gen. DO NOT EDIT.
from __future__ import annotations
from dataclasses import dataclass
from app.domain.entity.user import User


@dataclass
class UserDTO:
    id: str
    email: str
    name: str
    created_at_unix: int

    @classmethod
    def from_entity(cls, e: User) -> "UserDTO":
        return cls(
            id=e.id,
            email=e.email,
            name=e.name,
            created_at_unix=int(e.created_at.timestamp()),
        )

    def to_dict(self) -> dict:
        return self.__dict__


def from_entities(es: list[User]) -> list[UserDTO]:
    return [UserDTO.from_entity(e) for e in es]
