// Code generated by mss-protoc-gen. DO NOT EDIT.

import type { User } from "../entity/user.gen.js";

export interface UserRepository {
  save(user: User): Promise<void>;
  findById(id: string): Promise<User | null>;
  findByEmail(email: string): Promise<User | null>;
}
