// Code generated by mss-protoc-gen. DO NOT EDIT.

package repository

import (
	"context"
	"errors"
	"time"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"

	"github.com/example/manji-standard-server-go/pkg/domain/entity"
	"github.com/example/manji-standard-server-go/pkg/domain/repository"
)

type userModel struct {
	ID        string    `gorm:"column:id;primaryKey"`
	Email     string    `gorm:"column:email;uniqueIndex;not null"`
	Name      string    `gorm:"column:name;not null"`
	CreatedAt time.Time `gorm:"column:created_at;not null"`
}

func (userModel) TableName() string { return "users" }

func (m *userModel) toEntity() *entity.User {
	return entity.HydrateUser(
		m.ID,
		m.Email,
		m.Name,
		m.CreatedAt,
	)
}

func userToModel(e *entity.User) *userModel {
	return &userModel{
		ID:        e.ID,
		Email:     e.Email,
		Name:      e.Name,
		CreatedAt: e.CreatedAt,
	}
}

type postgresUserRepository struct {
	db *gorm.DB
}

func NewPostgresUserRepository(db *gorm.DB) repository.UserRepository {
	return &postgresUserRepository{db: db}
}

// AutoMigrateUser は開発用途のスキーマ同期ヘルパー。
// 本番では Goose / Atlas / Flyway 等のマイグレーションツールを使うこと。
func AutoMigrateUser(db *gorm.DB) error {
	return db.AutoMigrate(&userModel{})
}

var _ repository.UserRepository = (*postgresUserRepository)(nil)
var _ = time.Time{}

func (r *postgresUserRepository) SelectAll(ctx context.Context) ([]*entity.User, error) {
	var ms []userModel
	if err := r.db.WithContext(ctx).Find(&ms).Error; err != nil {
		return nil, err
	}
	out := make([]*entity.User, 0, len(ms))
	for i := range ms {
		out = append(out, ms[i].toEntity())
	}
	return out, nil
}

func (r *postgresUserRepository) SelectByPK(ctx context.Context, id string) (*entity.User, error) {
	var m userModel
	err := r.db.WithContext(ctx).Where("id = ?", id).First(&m).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return m.toEntity(), nil
}

func (r *postgresUserRepository) SelectByEmail(ctx context.Context, email string) (*entity.User, error) {
	var m userModel
	err := r.db.WithContext(ctx).Where("email = ?", email).First(&m).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return m.toEntity(), nil
}

func (r *postgresUserRepository) Insert(ctx context.Context, user *entity.User) error {
	m := userToModel(user)
	if err := r.db.WithContext(ctx).Create(m).Error; err != nil {
		if errors.Is(err, gorm.ErrDuplicatedKey) {
			return repository.ErrUserAlreadyExists
		}
		return err
	}
	return nil
}

func (r *postgresUserRepository) BulkInsert(ctx context.Context, users []*entity.User) error {
	if len(users) == 0 {
		return nil
	}
	return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		ms := make([]userModel, 0, len(users))
		for _, v := range users {
			ms = append(ms, *userToModel(v))
		}
		if err := tx.CreateInBatches(&ms, 100).Error; err != nil {
			if errors.Is(err, gorm.ErrDuplicatedKey) {
				return repository.ErrUserAlreadyExists
			}
			return err
		}
		return nil
	})
}

func (r *postgresUserRepository) Upsert(ctx context.Context, user *entity.User) error {
	m := userToModel(user)
	return r.db.WithContext(ctx).Clauses(clause.OnConflict{UpdateAll: true}).Create(m).Error
}

func (r *postgresUserRepository) BulkUpsert(ctx context.Context, users []*entity.User) error {
	if len(users) == 0 {
		return nil
	}
	return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		ms := make([]userModel, 0, len(users))
		for _, v := range users {
			ms = append(ms, *userToModel(v))
		}
		return tx.Clauses(clause.OnConflict{UpdateAll: true}).CreateInBatches(&ms, 100).Error
	})
}

func (r *postgresUserRepository) Update(ctx context.Context, user *entity.User) error {
	m := userToModel(user)
	res := r.db.WithContext(ctx).Model(&userModel{}).Where("id = ?", m.ID).Updates(m)
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return repository.ErrUserNotFound
	}
	return nil
}

func (r *postgresUserRepository) Delete(ctx context.Context, id string) error {
	res := r.db.WithContext(ctx).Where("id = ?", id).Delete(&userModel{})
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return repository.ErrUserNotFound
	}
	return nil
}

func (r *postgresUserRepository) BulkDelete(ctx context.Context, ids []string) error {
	if len(ids) == 0 {
		return nil
	}
	return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		res := tx.Where("id IN ?", ids).Delete(&userModel{})
		if res.Error != nil {
			return res.Error
		}
		if res.RowsAffected != int64(len(ids)) {
			return repository.ErrUserNotFound
		}
		return nil
	})
}

func (r *postgresUserRepository) DeleteAll(ctx context.Context) error {
	return r.db.WithContext(ctx).Where("1 = 1").Delete(&userModel{}).Error
}
