// Code generated by mss-protoc-gen. DO NOT EDIT.

package repository

import (
	"context"
	"sync"

	"github.com/example/manji-standard-server-go/pkg/domain/entity"
	"github.com/example/manji-standard-server-go/pkg/domain/repository"
)

type inMemoryUserRepository struct {
	mu    sync.RWMutex
	items map[string]*entity.User
}

func NewInMemoryUserRepository() repository.UserRepository {
	return &inMemoryUserRepository{items: make(map[string]*entity.User)}
}

func (r *inMemoryUserRepository) Save(_ context.Context, u *entity.User) error {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.items[u.ID] = u
	return nil
}

func (r *inMemoryUserRepository) FindByID(_ context.Context, id string) (*entity.User, error) {
	r.mu.RLock()
	defer r.mu.RUnlock()
	v, ok := r.items[id]
	if !ok {
		return nil, nil
	}
	return v, nil
}

func (r *inMemoryUserRepository) FindByEmail(_ context.Context, email string) (*entity.User, error) {
	r.mu.RLock()
	defer r.mu.RUnlock()
	for _, v := range r.items {
		if v.Email == email {
			return v, nil
		}
	}
	return nil, nil
}
