// Code generated by mss-protoc-gen. DO NOT EDIT.

package usecase

import (
	"context"

	"github.com/example/manji-standard-server-go/internal/dto"
)

type ListUsersInput struct{}

type ListUsersByCursorInput struct {
	Limit   int32
	AfterID string
}

type GetUserByEmailInput struct {
	Email string
}

type GetUserInput struct {
	ID string
}

type CreateUserInput struct {
	Email string
	Name  string
}

type BulkCreateUsersInput struct {
	Users []*CreateUserParams
}

type BulkUpsertUsersInput struct {
	Users []*UpsertUserParams
}

type UpsertUserInput struct {
	ID            string
	Email         string
	Name          string
	CreatedAtUnix int64
}

type UpdateUserInput struct {
	ID    string
	Email string
	Name  string
}

type BulkDeleteUsersInput struct {
	Ids []string
}

type DeleteUserInput struct {
	ID string
}

type DeleteAllUsersInput struct{}

type CreateUserParams struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

type UpsertUserParams struct {
	ID            string `json:"id"`
	Email         string `json:"email"`
	Name          string `json:"name"`
	CreatedAtUnix int64  `json:"created_at_unix"`
}

// UserUsecase は UserService の rpc 1 本につき 1 メソッドを持つ interface。
// 実装クラス（<Name>UsecaseImpl）はこの interface を実装する手書き層。
// 戻り値はすべて pkg/dto の DTO 型 / Output 型でクライアント JSON シリアライズ表現を一元管理する。
type UserUsecase interface {
	ListUsers(ctx context.Context, input ListUsersInput) ([]*dto.UserDTO, error)
	ListUsersByCursor(ctx context.Context, input ListUsersByCursorInput) ([]*dto.UserDTO, error)
	GetUserByEmail(ctx context.Context, input GetUserByEmailInput) (*dto.UserDTO, error)
	GetUser(ctx context.Context, input GetUserInput) (*dto.UserDTO, error)
	CreateUser(ctx context.Context, input CreateUserInput) (*dto.UserDTO, error)
	BulkCreateUsers(ctx context.Context, input BulkCreateUsersInput) ([]*dto.UserDTO, error)
	BulkUpsertUsers(ctx context.Context, input BulkUpsertUsersInput) ([]*dto.UserDTO, error)
	UpsertUser(ctx context.Context, input UpsertUserInput) (*dto.UserDTO, error)
	UpdateUser(ctx context.Context, input UpdateUserInput) (*dto.UserDTO, error)
	BulkDeleteUsers(ctx context.Context, input BulkDeleteUsersInput) error
	DeleteUser(ctx context.Context, input DeleteUserInput) error
	DeleteAllUsers(ctx context.Context, input DeleteAllUsersInput) error
}
