# Code generated by mss-protoc-gen. DO NOT EDIT.
from __future__ import annotations
from dataclasses import dataclass
from typing import Protocol
from pydantic import BaseModel
from app.dto.user import UserDTO

class CreateUserParams(BaseModel):
    email: str
    name: str


class UpsertUserParams(BaseModel):
    id: str
    email: str
    name: str
    created_at_unix: int


@dataclass
class ListUsersInput:
    pass


@dataclass
class ListUsersByCursorInput:
    limit: int
    after_id: str


@dataclass
class GetUserByEmailInput:
    email: str


@dataclass
class GetUserInput:
    id: str


@dataclass
class CreateUserInput:
    email: str
    name: str


@dataclass
class BulkCreateUsersInput:
    users: list[CreateUserParams]


@dataclass
class BulkUpsertUsersInput:
    users: list[UpsertUserParams]


@dataclass
class UpsertUserInput:
    id: str
    email: str
    name: str
    created_at_unix: int


@dataclass
class UpdateUserInput:
    id: str
    email: str
    name: str


@dataclass
class BulkDeleteUsersInput:
    ids: list[str]


@dataclass
class DeleteUserInput:
    id: str


@dataclass
class DeleteAllUsersInput:
    pass


class UserServiceUsecase(Protocol):
    def list_users(self, inp: ListUsersInput) -> list[UserDTO]: ...
    def list_users_by_cursor(self, inp: ListUsersByCursorInput) -> list[UserDTO]: ...
    def get_user_by_email(self, inp: GetUserByEmailInput) -> UserDTO | None: ...
    def get_user(self, inp: GetUserInput) -> UserDTO | None: ...
    def create_user(self, inp: CreateUserInput) -> UserDTO | None: ...
    def bulk_create_users(self, inp: BulkCreateUsersInput) -> list[UserDTO]: ...
    def bulk_upsert_users(self, inp: BulkUpsertUsersInput) -> list[UserDTO]: ...
    def upsert_user(self, inp: UpsertUserInput) -> UserDTO | None: ...
    def update_user(self, inp: UpdateUserInput) -> UserDTO | None: ...
    def bulk_delete_users(self, inp: BulkDeleteUsersInput) -> None: ...
    def delete_user(self, inp: DeleteUserInput) -> None: ...
    def delete_all_users(self, inp: DeleteAllUsersInput) -> None: ...
