// Code generated by mss-protoc-gen. DO NOT EDIT.

package handler

import (
	"encoding/json"
	"errors"
	"net/http"
	"strconv"
	"github.com/example/manji-standard-server-go/internal/domain/repository"
	"github.com/example/manji-standard-server-go/internal/usecase"
)

type UserHandler struct {
	usecase usecase.UserUsecase
}

func NewUserHandler(uc usecase.UserUsecase) *UserHandler {
	return &UserHandler{usecase: uc}
}

func (h *UserHandler) writeError(w http.ResponseWriter, err error) {
	status := http.StatusBadRequest
	if errors.Is(err, repository.ErrUserNotFound) {
		status = http.StatusNotFound
	}
	if errors.Is(err, repository.ErrUserAlreadyExists) {
		status = http.StatusConflict
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(map[string]string{"error": err.Error()})
}

// GET /api/users
func (h *UserHandler) ListUsers(w http.ResponseWriter, r *http.Request) {
	list, err := h.usecase.ListUsers(r.Context(), usecase.ListUsersInput{})
	if err != nil {
		h.writeError(w, err)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_ = json.NewEncoder(w).Encode(list)
}

// GET /api/users/cursor
func (h *UserHandler) ListUsersByCursor(w http.ResponseWriter, r *http.Request) {
	_urlq := r.URL.Query()
	_limit, _ := strconv.Atoi(_urlq.Get("limit"))
	_afterId := _urlq.Get("after_id")
	list, err := h.usecase.ListUsersByCursor(r.Context(), usecase.ListUsersByCursorInput{
		Limit:   int32(_limit),
		AfterID: _afterId,
	})
	if err != nil {
		h.writeError(w, err)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_ = json.NewEncoder(w).Encode(list)
}

// GET /api/users/by-email
func (h *UserHandler) GetUserByEmail(w http.ResponseWriter, r *http.Request) {
	_urlq := r.URL.Query()
	_email := _urlq.Get("email")
	result, err := h.usecase.GetUserByEmail(r.Context(), usecase.GetUserByEmailInput{
		Email: _email,
	})
	if err != nil {
		h.writeError(w, err)
		return
	}
	if result == nil {
		h.writeError(w, repository.ErrUserNotFound)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_ = json.NewEncoder(w).Encode(result)
}

// GET /api/users/{id}
func (h *UserHandler) GetUser(w http.ResponseWriter, r *http.Request) {
	result, err := h.usecase.GetUser(r.Context(), usecase.GetUserInput{
		ID: r.PathValue("id"),
	})
	if err != nil {
		h.writeError(w, err)
		return
	}
	if result == nil {
		h.writeError(w, repository.ErrUserNotFound)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_ = json.NewEncoder(w).Encode(result)
}

type CreateUserBody struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

// POST /api/users
func (h *UserHandler) CreateUser(w http.ResponseWriter, r *http.Request) {
	var body CreateUserBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		_ = json.NewEncoder(w).Encode(map[string]string{"error": "invalid body"})
		return
	}
	result, err := h.usecase.CreateUser(r.Context(), usecase.CreateUserInput{
		Email: body.Email,
		Name:  body.Name,
	})
	if err != nil {
		h.writeError(w, err)
		return
	}
	if result == nil {
		h.writeError(w, repository.ErrUserNotFound)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_ = json.NewEncoder(w).Encode(result)
}

type BulkCreateUsersBody struct {
	Users []*usecase.CreateUserParams `json:"users"`
}

// POST /api/users/bulk
func (h *UserHandler) BulkCreateUsers(w http.ResponseWriter, r *http.Request) {
	var body BulkCreateUsersBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		_ = json.NewEncoder(w).Encode(map[string]string{"error": "invalid body"})
		return
	}
	list, err := h.usecase.BulkCreateUsers(r.Context(), usecase.BulkCreateUsersInput{
		Users: body.Users,
	})
	if err != nil {
		h.writeError(w, err)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusCreated)
	_ = json.NewEncoder(w).Encode(list)
}

type BulkUpsertUsersBody struct {
	Users []*usecase.UpsertUserParams `json:"users"`
}

// PUT /api/users/bulk
func (h *UserHandler) BulkUpsertUsers(w http.ResponseWriter, r *http.Request) {
	var body BulkUpsertUsersBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		_ = json.NewEncoder(w).Encode(map[string]string{"error": "invalid body"})
		return
	}
	list, err := h.usecase.BulkUpsertUsers(r.Context(), usecase.BulkUpsertUsersInput{
		Users: body.Users,
	})
	if err != nil {
		h.writeError(w, err)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_ = json.NewEncoder(w).Encode(list)
}

type UpsertUserBody struct {
	Email         string `json:"email"`
	Name          string `json:"name"`
	CreatedAtUnix int64  `json:"created_at_unix"`
}

// PUT /api/users/{id}
func (h *UserHandler) UpsertUser(w http.ResponseWriter, r *http.Request) {
	var body UpsertUserBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		_ = json.NewEncoder(w).Encode(map[string]string{"error": "invalid body"})
		return
	}
	result, err := h.usecase.UpsertUser(r.Context(), usecase.UpsertUserInput{
		ID:            r.PathValue("id"),
		Email:         body.Email,
		Name:          body.Name,
		CreatedAtUnix: body.CreatedAtUnix,
	})
	if err != nil {
		h.writeError(w, err)
		return
	}
	if result == nil {
		h.writeError(w, repository.ErrUserNotFound)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_ = json.NewEncoder(w).Encode(result)
}

type UpdateUserBody struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

// PATCH /api/users/{id}
func (h *UserHandler) UpdateUser(w http.ResponseWriter, r *http.Request) {
	var body UpdateUserBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		_ = json.NewEncoder(w).Encode(map[string]string{"error": "invalid body"})
		return
	}
	result, err := h.usecase.UpdateUser(r.Context(), usecase.UpdateUserInput{
		ID:    r.PathValue("id"),
		Email: body.Email,
		Name:  body.Name,
	})
	if err != nil {
		h.writeError(w, err)
		return
	}
	if result == nil {
		h.writeError(w, repository.ErrUserNotFound)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_ = json.NewEncoder(w).Encode(result)
}

type BulkDeleteUsersBody struct {
	Ids []string `json:"ids"`
}

// POST /api/users/bulk-delete
func (h *UserHandler) BulkDeleteUsers(w http.ResponseWriter, r *http.Request) {
	var body BulkDeleteUsersBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		_ = json.NewEncoder(w).Encode(map[string]string{"error": "invalid body"})
		return
	}
	if err := h.usecase.BulkDeleteUsers(r.Context(), usecase.BulkDeleteUsersInput{
		Ids: body.Ids,
	}); err != nil {
		h.writeError(w, err)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

// DELETE /api/users/{id}
func (h *UserHandler) DeleteUser(w http.ResponseWriter, r *http.Request) {
	if err := h.usecase.DeleteUser(r.Context(), usecase.DeleteUserInput{
		ID: r.PathValue("id"),
	}); err != nil {
		h.writeError(w, err)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

// DELETE /api/users
func (h *UserHandler) DeleteAllUsers(w http.ResponseWriter, r *http.Request) {
	if err := h.usecase.DeleteAllUsers(r.Context(), usecase.DeleteAllUsersInput{}); err != nil {
		h.writeError(w, err)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}
