// Code generated by mss-protoc-gen. DO NOT EDIT.

import { vi } from "vitest";
import type { User } from "../../entity/user.gen.js";
import type { UserRepository } from "../user-repository.gen.js";

export class MockUserRepository implements UserRepository {
  selectAll = vi.fn<() => Promise<User[]>>(async () => []);
  selectByPk = vi.fn<(id: string) => Promise<User | null>>(async () => null);
  selectByEmail = vi.fn<(email: string) => Promise<User | null>>(async () => null);
  insert = vi.fn<(user: User) => Promise<void>>(async () => {});
  bulkInsert = vi.fn<(users: User[]) => Promise<void>>(async () => {});
  upsert = vi.fn<(user: User) => Promise<void>>(async () => {});
  bulkUpsert = vi.fn<(users: User[]) => Promise<void>>(async () => {});
  update = vi.fn<(user: User) => Promise<void>>(async () => {});
  delete = vi.fn<(id: string) => Promise<void>>(async () => {});
  bulkDelete = vi.fn<(ids: string[]) => Promise<void>>(async () => {});
  deleteAll = vi.fn<() => Promise<void>>(async () => {});
}
