// Code generated by mss-protoc-gen. DO NOT EDIT.

import { bigint, boolean, integer, pgTable, text, timestamp } from "drizzle-orm/pg-core";

// {{.Plural}}Table は {{.Name}} の永続化スキーマ(Drizzle ORM)。
// entity 自身が ORM 制約(primaryKey / unique / notNull / カラム型)を所有する。
// 別 DB 実装(MySQL 等)へ差し替える場合はテンプレートを差し替える。
export const {{.Plural}}Table = pgTable("{{.Plural}}", {
{{- range .Fields}}
  {{.name}}: {{drizzleColumn .}},
{{- end}}
});

// 未使用 import 抑止(integer / bigint / boolean はフィールド構成次第で未使用になる)
const _unused = { text, integer, bigint, boolean, timestamp };
void _unused;

export type {{.Name}}Row = typeof {{.Plural}}Table.$inferSelect;
export type {{.Name}}Insert = typeof {{.Plural}}Table.$inferInsert;

export type {{.Name}}Props = {
{{- range .Fields}}
  {{.name}}: {{.type}};
{{- end}}
};

export class {{.Name}} {
{{- range .Fields}}
  readonly {{.name}}: {{.type}};
{{- end}}

  private constructor(props: {{.Name}}Props) {
{{- range .Fields}}
    this.{{.name}} = props.{{.name}};
{{- end}}
  }

  static create(props: {{.Name}}Props): {{.Name}} {
{{- range .Fields}}
{{- if .isPk}}
    if (!props.{{.name}}) {
      throw new Error("{{.name}} is required");
    }
{{- end}}
{{- if and .isRequired (eq .type "string")}}
    const {{.name}} = props.{{.name}}.trim();
    if (!{{.name}}) {
      throw new Error("{{.name}} is required");
    }
{{- end}}
{{- if .isEmail}}
    const {{.name}} = props.{{.name}}.trim();
    if (!{{.name}} || !{{.name}}.includes("@")) {
      throw new Error("{{.name}} is invalid");
    }
{{- end}}
{{- end}}
    return new {{.Name}}({
{{- range .Fields}}
{{- if or .isEmail (and .isRequired (eq .type "string"))}}
      {{.name}},
{{- else}}
      {{.name}}: props.{{.name}},
{{- end}}
{{- end}}
    });
  }

  /** 永続化層から復元した値で {{.Name}} を組み立てる(バリデーションなし)。通常コードパスでは create() を使うこと。 */
  static hydrate(props: {{.Name}}Props): {{.Name}} {
    return new {{.Name}}(props);
  }
}
