# Code generated by mss-protoc-gen. DO NOT EDIT.
from __future__ import annotations
from datetime import datetime  # noqa: F401
from sqlalchemy import String, BigInteger, Integer, Boolean, Float, DateTime  # noqa: F401
from sqlalchemy.orm import Mapped, mapped_column
from app.domain.entity.base import Base


class User(Base):
    __tablename__ = "users"

    id: Mapped[str] = mapped_column(String(255), primary_key=True)
    email: Mapped[str] = mapped_column(String(255), unique=True, nullable=True)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=True)

    @classmethod
    def new(cls, id: str, email: str, name: str, created_at: datetime) -> "User":
        # 生成された validation(@pk / @required / @email)
        if not id:
            raise ValueError("id is required")
        email = (email or "").strip()
        if not email or "@" not in email:
            raise ValueError("email is invalid")
        name = (name or "").strip()
        if not name:
            raise ValueError("name is required")
        return cls(id=id, email=email, name=name, created_at=created_at)
