// Code generated by mss-protoc-gen. DO NOT EDIT.

import type { User } from "../domain/entity/user.gen.js";


export type CreateUserInput = {
  email: string;
  name: string;
};

export type GetUserInput = {
  id: string;
};

/**
 * UserUsecase は UserService の rpc 1 本につき 1 メソッドを持つ interface。
 * 実装クラス（UserUsecaseImpl）はこの interface を実装する手書き層。
 */
export interface UserUsecase {
  createUser(input: CreateUserInput): Promise<User | null>;
  getUser(input: GetUserInput): Promise<User | null>;
}
