// Code generated by mss-protoc-gen. DO NOT EDIT.

import type { UserDTO } from "../dto/user.gen";


/**
 * CreateUserParams は rpc 入力の非 entity message を TS 型として表したもの。
 * snake_case のキーは proto field 名(クライアント wire format)に揃えてある。
 */
export type CreateUserParams = {
  email: string;
  name: string;
};


/**
 * UpsertUserParams は rpc 入力の非 entity message を TS 型として表したもの。
 * snake_case のキーは proto field 名(クライアント wire format)に揃えてある。
 */
export type UpsertUserParams = {
  id: string;
  email: string;
  name: string;
  created_at_unix: number;
};




export type ListUsersInput = Record<string, never>;

export type ListUsersByCursorInput = {
  limit: number;
  afterId: string;
};

export type GetUserByEmailInput = {
  email: string;
};

export type GetUserInput = {
  id: string;
};

export type CreateUserInput = {
  email: string;
  name: string;
};

export type BulkCreateUsersInput = {
  users: CreateUserParams[];
};

export type BulkUpsertUsersInput = {
  users: UpsertUserParams[];
};

export type UpsertUserInput = {
  id: string;
  email: string;
  name: string;
  createdAtUnix: number;
};

export type UpdateUserInput = {
  id: string;
  email: string;
  name: string;
};

export type BulkDeleteUsersInput = {
  ids: string[];
};

export type DeleteUserInput = {
  id: string;
};

export type DeleteAllUsersInput = Record<string, never>;

/**
 * UserUsecase は UserService の rpc 1 本につき 1 メソッドを持つ interface。
 * 実装クラス(UserUsecaseImpl)はこの interface を実装する手書き層。
 * 戻り値はすべて DTO に変換済み(クライアント JSON 表現の境界)。
 */
export interface UserUsecase {
  listUsers(input: ListUsersInput): Promise<UserDTO[]>;
  listUsersByCursor(input: ListUsersByCursorInput): Promise<UserDTO[]>;
  getUserByEmail(input: GetUserByEmailInput): Promise<UserDTO | null>;
  getUser(input: GetUserInput): Promise<UserDTO | null>;
  createUser(input: CreateUserInput): Promise<UserDTO | null>;
  bulkCreateUsers(input: BulkCreateUsersInput): Promise<UserDTO[]>;
  bulkUpsertUsers(input: BulkUpsertUsersInput): Promise<UserDTO[]>;
  upsertUser(input: UpsertUserInput): Promise<UserDTO | null>;
  updateUser(input: UpdateUserInput): Promise<UserDTO | null>;
  bulkDeleteUsers(input: BulkDeleteUsersInput): Promise<void>;
  deleteUser(input: DeleteUserInput): Promise<void>;
  deleteAllUsers(input: DeleteAllUsersInput): Promise<void>;
}
