// Code generated by mss-protoc-gen. DO NOT EDIT.

package usecase

import (
	"context"

	"github.com/example/manji-standard-server-go/pkg/domain/entity"
)

type CreateUserInput struct {
	Email string
	Name  string
}

type GetUserInput struct {
	ID string
}

// UserUsecase は UserService の rpc 1 本につき 1 メソッドを持つ interface。
// 実装クラス（<Name>UsecaseImpl）はこの interface を実装する手書き層。
type UserUsecase interface {
	CreateUser(ctx context.Context, input CreateUserInput) (*entity.User, error)
	GetUser(ctx context.Context, input GetUserInput) (*entity.User, error)
}
