// Code generated by mss-protoc-gen. DO NOT EDIT.

package dto

import (
	"time"

	"github.com/example/manji-standard-server-go/internal/domain/entity"
)

// UserDTO は User エンティティをクライアントへ返すための JSON シリアライズ型。
// json タグはここで一元管理する。entity 側は GORM タグのみ持つ。
type UserDTO struct {
	ID            string `json:"id"`
	Email         string `json:"email"`
	Name          string `json:"name"`
	CreatedAtUnix int64  `json:"created_at_unix"`
}

// FromUser は entity.User を UserDTO に変換する。
// nil を渡したら nil を返す。
func FromUser(e *entity.User) *UserDTO {
	if e == nil {
		return nil
	}
	return &UserDTO{
		ID:            e.ID,
		Email:         e.Email,
		Name:          e.Name,
		CreatedAtUnix: e.CreatedAt.Unix(),
	}
}

// FromUsers は []*entity.User を []*UserDTO に変換する。
func FromUsers(es []*entity.User) []*UserDTO {
	out := make([]*UserDTO, 0, len(es))
	for _, e := range es {
		out = append(out, FromUser(e))
	}
	return out
}

var _ = time.Time{}
