// Code generated by mss-protoc-gen. DO NOT EDIT.

import type { Context } from "hono";


import type { User } from "../domain/entity/user.gen.js";
import {
  UserNotFoundError,
  UserAlreadyExistsError,
} from "../domain/repository/user-repository.gen.js";
import type { UserUsecase } from "../usecase/user-usecase-interface.gen.js";


function userToJson(e: User) {
  return {
    id: e.id,
    email: e.email,
    name: e.name,
    created_at_unix: Math.floor(e.createdAt.getTime() / 1000),
  };
}


type CreateUserBody = {
  email?: string;
  name?: string;
};



export class UserRestHandler {
  constructor(private readonly usecase: UserUsecase) {}

  private handleError(c: Context, err: unknown) {
    const message = err instanceof Error ? err.message : "unknown error";
    if (err instanceof UserNotFoundError) return c.json({ error: message }, 404);
    if (err instanceof UserAlreadyExistsError) return c.json({ error: message }, 409);
    return c.json({ error: message }, 400);
  }

  // POST /api/users
  async createUser(c: Context) {
    let body: CreateUserBody;
    try {
      body = await c.req.json();
    } catch {
      return c.json({ error: "invalid body" }, 400);
    }
    try {
      const input = {
        email: body.email ?? "",
        name: body.name ?? "",
      };
      const result = await this.usecase.createUser(input);
      if (!result) return c.json({ error: "user not found" }, 404);
      return c.json(userToJson(result), 201);
    } catch (err) {
      return this.handleError(c, err);
    }
  }

  // GET /api/users/{id}
  async getUser(c: Context) {
    try {
      const input = {
        id: c.req.param("id") ?? "",
      };
      const result = await this.usecase.getUser(input);
      if (!result) return c.json({ error: "user not found" }, 404);
      return c.json(userToJson(result), 200);
    } catch (err) {
      return this.handleError(c, err);
    }
  }

}
