// Code generated by mss-protoc-gen. DO NOT EDIT.

package handler

import (
	"encoding/json"
	"errors"
	"net/http"

	"{{.ImportEntity}}"
	"{{.ImportRepository}}"
	"{{.ImportUsecase}}"
)

type {{.HandlerTypeName}} struct {
	usecase usecase.{{.UsecaseTypeName}}
}

func New{{.HandlerTypeName}}(uc usecase.{{.UsecaseTypeName}}) *{{.HandlerTypeName}} {
	return &{{.HandlerTypeName}}{usecase: uc}
}
{{range .UsedEntities}}
func {{.LowerFirst}}ToJSON(e *entity.{{.Name}}) map[string]any {
	if e == nil {
		return nil
	}
	return map[string]any{
{{- range .Fields}}
{{- if .IsTimestamp}}
		"{{.SnakeName}}_unix": e.{{.GoName}}.Unix(),
{{- else}}
		"{{.SnakeName}}": e.{{.GoName}},
{{- end}}
{{- end}}
	}
}
{{end}}
func (h *{{.HandlerTypeName}}) writeError(w http.ResponseWriter, err error) {
	status := http.StatusBadRequest
{{- range .UsedEntities}}
	if errors.Is(err, repository.Err{{.Name}}NotFound) {
		status = http.StatusNotFound
	}
	if errors.Is(err, repository.Err{{.Name}}AlreadyExists) {
		status = http.StatusConflict
	}
{{- end}}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(map[string]string{"error": err.Error()})
}
{{range .Methods}}
{{- if .Http}}
{{- if .HasBodyFields}}

type {{.Name}}Body struct {
{{- range .BodyFields}}
	{{.GoName}} {{.GoType}} `json:"{{.JsonName}}"`
{{- end}}
}
{{- end}}

// {{.Http.Method}} {{.Http.Path}}
func (h *{{$.HandlerTypeName}}) {{.Name}}(w http.ResponseWriter, r *http.Request) {
{{- if .HasBodyFields}}
	var body {{.Name}}Body
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusBadRequest)
		_ = json.NewEncoder(w).Encode(map[string]string{"error": "invalid body"})
		return
	}
{{- end}}
{{- if .ReturnsEntity}}
	result, err := h.usecase.{{.Name}}(r.Context(), usecase.{{.InputTypeName}}{
{{- range .PathParamFields}}
		{{.GoName}}: r.PathValue("{{.JsonName}}"),
{{- end}}
{{- range .BodyFields}}
		{{.GoName}}: body.{{.GoName}},
{{- end}}
	})
	if err != nil {
		h.writeError(w, err)
		return
	}
	if result == nil {
		h.writeError(w, repository.Err{{.EntityGoName}}NotFound)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader({{if eq .Http.Method "POST"}}http.StatusCreated{{else}}http.StatusOK{{end}})
	_ = json.NewEncoder(w).Encode({{.EntityLowerFirst}}ToJSON(result))
{{- else if .ReturnsList}}
	list, err := h.usecase.{{.Name}}(r.Context(), usecase.{{.InputTypeName}}{
{{- range .PathParamFields}}
		{{.GoName}}: r.PathValue("{{.JsonName}}"),
{{- end}}
{{- range .BodyFields}}
		{{.GoName}}: body.{{.GoName}},
{{- end}}
	})
	if err != nil {
		h.writeError(w, err)
		return
	}
	out := make([]map[string]any, 0, len(list))
	for _, e := range list {
		out = append(out, {{.EntityLowerFirst}}ToJSON(e))
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	_ = json.NewEncoder(w).Encode(out)
{{- else}}
	if err := h.usecase.{{.Name}}(r.Context(), usecase.{{.InputTypeName}}{
{{- range .PathParamFields}}
		{{.GoName}}: r.PathValue("{{.JsonName}}"),
{{- end}}
{{- range .BodyFields}}
		{{.GoName}}: body.{{.GoName}},
{{- end}}
	}); err != nil {
		h.writeError(w, err)
		return
	}
	w.WriteHeader(http.StatusNoContent)
{{- end}}
}
{{- end}}
{{end}}
