// Code generated by mss-protoc-gen. DO NOT EDIT.

package mock

import (
	"context"

	"github.com/example/manji-standard-server-go/internal/domain/entity"
	"github.com/example/manji-standard-server-go/internal/domain/repository"
)

// MockUserRepository は repository.UserRepository のテスト用スタブ。
// 各 Func フィールドにスタブ関数を差し込み、未設定ならゼロ値を返す。
type MockUserRepository struct {
	SelectAllFunc      func(ctx context.Context) ([]*entity.User, error)
	SelectByPKFunc     func(ctx context.Context, id string) (*entity.User, error)
	SelectByEmailFunc  func(ctx context.Context, email string) (*entity.User, error)
	InsertFunc         func(ctx context.Context, user *entity.User) error
	BulkInsertFunc     func(ctx context.Context, users []*entity.User) error
	UpsertFunc         func(ctx context.Context, user *entity.User) error
	BulkUpsertFunc     func(ctx context.Context, users []*entity.User) error
	UpdateFunc         func(ctx context.Context, user *entity.User) error
	DeleteFunc         func(ctx context.Context, id string) error
	BulkDeleteFunc     func(ctx context.Context, ids []string) error
	DeleteAllFunc      func(ctx context.Context) error
	SelectByCursorFunc func(ctx context.Context, limit int, after *string) ([]*entity.User, error)
}

var _ repository.UserRepository = (*MockUserRepository)(nil)

func (m *MockUserRepository) SelectAll(ctx context.Context) ([]*entity.User, error) {
	if m.SelectAllFunc != nil {
		return m.SelectAllFunc(ctx)
	}
	return nil, nil
}

func (m *MockUserRepository) SelectByPK(ctx context.Context, id string) (*entity.User, error) {
	if m.SelectByPKFunc != nil {
		return m.SelectByPKFunc(ctx, id)
	}
	return nil, nil
}

func (m *MockUserRepository) SelectByEmail(ctx context.Context, email string) (*entity.User, error) {
	if m.SelectByEmailFunc != nil {
		return m.SelectByEmailFunc(ctx, email)
	}
	return nil, nil
}

func (m *MockUserRepository) Insert(ctx context.Context, user *entity.User) error {
	if m.InsertFunc != nil {
		return m.InsertFunc(ctx, user)
	}
	return nil
}

func (m *MockUserRepository) BulkInsert(ctx context.Context, users []*entity.User) error {
	if m.BulkInsertFunc != nil {
		return m.BulkInsertFunc(ctx, users)
	}
	return nil
}

func (m *MockUserRepository) Upsert(ctx context.Context, user *entity.User) error {
	if m.UpsertFunc != nil {
		return m.UpsertFunc(ctx, user)
	}
	return nil
}

func (m *MockUserRepository) BulkUpsert(ctx context.Context, users []*entity.User) error {
	if m.BulkUpsertFunc != nil {
		return m.BulkUpsertFunc(ctx, users)
	}
	return nil
}

func (m *MockUserRepository) Update(ctx context.Context, user *entity.User) error {
	if m.UpdateFunc != nil {
		return m.UpdateFunc(ctx, user)
	}
	return nil
}

func (m *MockUserRepository) Delete(ctx context.Context, id string) error {
	if m.DeleteFunc != nil {
		return m.DeleteFunc(ctx, id)
	}
	return nil
}

func (m *MockUserRepository) BulkDelete(ctx context.Context, ids []string) error {
	if m.BulkDeleteFunc != nil {
		return m.BulkDeleteFunc(ctx, ids)
	}
	return nil
}

func (m *MockUserRepository) DeleteAll(ctx context.Context) error {
	if m.DeleteAllFunc != nil {
		return m.DeleteAllFunc(ctx)
	}
	return nil
}

func (m *MockUserRepository) SelectByCursor(ctx context.Context, limit int, after *string) ([]*entity.User, error) {
	if m.SelectByCursorFunc != nil {
		return m.SelectByCursorFunc(ctx, limit, after)
	}
	return nil, nil
}
