// Code generated by mss-protoc-gen. DO NOT EDIT.

import type { Context } from "hono";

{{range .UsedEntities}}
import type { {{.Name}} } from "../domain/entity/{{.Kebab}}.gen.js";
import {
  {{.Name}}NotFoundError,
  {{.Name}}AlreadyExistsError,
} from "../domain/repository/{{.Kebab}}-repository.gen.js";
{{- end}}
import type { {{.UsecaseTypeName}} } from "../usecase/{{.Kebab}}-usecase-interface.gen.js";

{{range .UsedEntities}}
function {{.LowerFirst}}ToJson(e: {{.Name}}) {
  return {
{{- range .Fields}}
{{- if .isTimestamp}}
    {{.snakeName}}_unix: Math.floor(e.{{.name}}.getTime() / 1000),
{{- else}}
    {{.snakeName}}: e.{{.name}},
{{- end}}
{{- end}}
  };
}
{{end}}
{{range .Methods}}
{{- if .HasBodyFields}}
type {{.rpcName}}Body = {
{{- range .BodyFields}}
  {{.name}}?: {{.type}};
{{- end}}
};
{{- end}}
{{end}}

export class {{.HandlerClassName}} {
  constructor(private readonly usecase: {{.UsecaseTypeName}}) {}

  private handleError(c: Context, err: unknown) {
    const message = err instanceof Error ? err.message : "unknown error";
{{- range .UsedEntities}}
    if (err instanceof {{.Name}}NotFoundError) return c.json({ error: message }, 404);
    if (err instanceof {{.Name}}AlreadyExistsError) return c.json({ error: message }, 409);
{{- end}}
    return c.json({ error: message }, 400);
  }
{{range .Methods}}
{{- if .Http}}
  // {{.Http.Method}} {{.Http.Path}}
  async {{.lowerName}}(c: Context) {
{{- if .HasBodyFields}}
    let body: {{.rpcName}}Body;
    try {
      body = await c.req.json();
    } catch {
      return c.json({ error: "invalid body" }, 400);
    }
{{- end}}
    try {
      const input = {
{{- range .PathParamFields}}
        {{.name}}: c.req.param("{{.name}}") ?? "",
{{- end}}
{{- range .BodyFields}}
{{- if eq .type "string"}}
        {{.name}}: body.{{.name}} ?? "",
{{- end}}
{{- if eq .type "number"}}
        {{.name}}: body.{{.name}} ?? 0,
{{- end}}
{{- if eq .type "boolean"}}
        {{.name}}: body.{{.name}} ?? false,
{{- end}}
{{- end}}
      };
{{- if .ReturnsEntity}}
      const result = await this.usecase.{{.lowerName}}(input);
      if (!result) return c.json({ error: "{{.EntityLowerFirst}} not found" }, 404);
      return c.json({{.EntityLowerFirst}}ToJson(result), {{if eq .Http.Method "POST"}}201{{else}}200{{end}});
{{- end}}
{{- if .ReturnsList}}
      const list = await this.usecase.{{.lowerName}}(input);
      return c.json(list.map({{.EntityLowerFirst}}ToJson), 200);
{{- end}}
{{- if .ReturnsEmpty}}
      await this.usecase.{{.lowerName}}(input);
      return c.body(null, 204);
{{- end}}
    } catch (err) {
      return this.handleError(c, err);
    }
  }
{{- end}}
{{end}}
}
