// mss-protoc-gen (frontend port) — proto 契約 → frontend(型/APIクライアント/CRUD UI/page)生成。
// self-contained: buf/protoc/python 不要。manji proto の文法を直接パースする。
// 生成物ヘッダ: "// Code generated by mss-protoc-gen. DO NOT EDIT."
// 設計: ../../DESIGN.md, KB: [[contract-to-ui-codegen]] / [[selection-design-pattern]]
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..");
const HEADER = "// Code generated by mss-protoc-gen. DO NOT EDIT.\n";

// ---------- proto parser ----------
const SCALAR = { string: "string", int64: "number", int32: "number", bool: "boolean", double: "number" };
const annosFrom = (lead) => {
  const out = {};
  const re = /@(\w+)(?:\s+([^\n@]+))?/g;
  let m;
  while ((m = re.exec(lead.join("\n")))) out[m[1]] = (m[2] || "").trim();
  return out;
};

function parseProto(text) {
  const lines = text.split("\n");
  const messages = [], services = [];
  let pkg = "", lead = [], i = 0;
  const takeLead = () => { const a = annosFrom(lead); lead = []; return a; };
  while (i < lines.length) {
    const line = lines[i].trim();
    if (line.startsWith("//")) { lead.push(line.slice(2)); i++; continue; }
    if (line === "") { lead = []; i++; continue; }
    if (line.startsWith("package ")) { pkg = line.slice(8).replace(";", "").trim(); lead = []; i++; continue; }
    if (/^(syntax|option|import)\b/.test(line)) { lead = []; i++; continue; }
    let m;
    const oneLineEmpty = /\{\s*\}\s*$/.test(line); // `message X {}` のような1行空定義
    if ((m = line.match(/^message\s+(\w+)\s*\{/))) {
      const annotations = takeLead();
      if (oneLineEmpty) { messages.push({ name: m[1], annotations, fields: [] }); i++; continue; }
      const r = parseBlock(lines, i + 1, "field");
      messages.push({ name: m[1], annotations, fields: r.items });
      i = r.next; continue;
    }
    if ((m = line.match(/^enum\s+(\w+)\s*\{/))) {
      lead = [];
      i = oneLineEmpty ? i + 1 : parseBlock(lines, i + 1, "skip").next; continue;
    }
    if ((m = line.match(/^service\s+(\w+)\s*\{/))) {
      takeLead();
      if (oneLineEmpty) { services.push({ name: m[1], rpcs: [] }); i++; continue; }
      const r = parseBlock(lines, i + 1, "rpc");
      services.push({ name: m[1], rpcs: r.items });
      i = r.next; continue;
    }
    lead = []; i++;
  }
  return { package: pkg, messages, services };
}

function parseBlock(lines, start, kind) {
  const items = []; let lead = [], i = start;
  for (; i < lines.length; i++) {
    const line = lines[i].trim();
    if (line === "}") return { items, next: i + 1 };
    if (line.startsWith("//")) { lead.push(line.slice(2)); continue; }
    if (line === "") { lead = []; continue; }
    if (kind === "field") {
      const m = line.match(/^(?:(repeated|optional)\s+)?([\w.]+)\s+(\w+)\s*=\s*\d+\s*;/);
      if (m) { items.push({ name: m[3], type: m[2].split(".").pop(), repeated: m[1] === "repeated", annotations: annosFrom(lead) }); }
      lead = [];
    } else if (kind === "rpc") {
      const m = line.match(/^rpc\s+(\w+)\s*\(\s*([\w.]+)\s*\)\s*returns\s*\(\s*([\w.]+)\s*\)\s*;/);
      if (m) {
        const a = annosFrom(lead); const p = (a.http || "").split(/\s+/);
        items.push({ name: m[1], input: m[2].split(".").pop(), output: m[3].split(".").pop(),
          httpMethod: p[0] || "GET", httpPath: p[1] || "/", pathParams: [...(p[1] || "").matchAll(/\{(\w+)\}/g)].map((x) => x[1]) });
      }
      lead = [];
    }
  }
  return { items, next: i };
}

// ---------- model helpers ----------
const snake = (s) => s.replace(/(?<!^)([A-Z])/g, "_$1").toLowerCase();
const camel = (s) => s.charAt(0).toLowerCase() + s.slice(1);
const humanize = (s) => s.replace(/_unix$/, "").replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
const tsType = (f) => (SCALAR[f.type] || f.type) + (f.repeated ? "[]" : "");
const isMsg = (t) => /^[A-Z]/.test(t);

function fieldMeta(f) {
  const a = f.annotations;
  const isPk = "pk" in a, isTs = "timestamp" in a;
  const listRole = a.list || (isPk ? "secondary" : (f.type === "string" && !isTs ? "primary" : "secondary"));
  const widget = a.form || (isPk || isTs ? "readonly" : ("email" in a ? "email" : "text"));
  return {
    ...f, label: (a.label || humanize(f.name)).replace(/"/g, ""), ts: tsType(f),
    isPk, isTs, isRequired: "required" in a, isEmail: "email" in a, isUnique: "unique" in a,
    listRole, widget, editable: !(isPk || isTs),
  };
}

// ---------- templates (string builders; no nested template literals) ----------
function tplTypes(ent, msgByName) {
  const L = [HEADER, "// entity + request/response 型\n"];
  const emit = (m) => {
    L.push("export interface " + m.name + " {");
    for (const f of m.fields) {
      const t = isMsg(f.type) ? f.type + (f.repeated ? "[]" : "") : tsType(f);
      L.push("  " + f.name + ": " + t + ";");
    }
    L.push("}\n");
  };
  emit(ent);
  return L.join("\n");
}

function tplClient(ent, svc, msgByName) {
  const E = ent.name;
  const L = [HEADER, 'import { apiFetch } from "../../lib/api";'];
  L.push('import type { ' + E + ' } from "../types/' + snake(E) + '";\n');
  for (const r of svc.rpcs) {
    const req = msgByName[r.input];
    const fields = (req?.fields || []);
    if (fields.some((f) => isMsg(f.type))) continue; // nested-param bulk は初回除外
    // path params vs query vs body
    const path = r.httpPath;
    const pathParams = r.pathParams;
    const isBody = ["POST", "PUT", "PATCH"].includes(r.httpMethod);
    const args = [];
    for (const p of pathParams) args.push(p + ": string");
    const bodyFields = isBody ? fields.filter((f) => !pathParams.includes(f.name)) : [];
    const queryFields = !isBody ? fields.filter((f) => !pathParams.includes(f.name)) : [];
    if (bodyFields.length) args.push("body: { " + bodyFields.map((f) => f.name + ": " + tsType(f)).join("; ") + " }");
    for (const f of queryFields) args.push(f.name + "?: " + tsType(f));
    // return type
    const resp = msgByName[r.output];
    const rf = resp?.fields || [];
    let ret = "void";
    if (rf.length === 1 && rf[0].type === E) ret = rf[0].repeated ? E + "[]" : E;
    // build url
    let urlExpr = '"' + path + '"';
    for (const p of pathParams) urlExpr = urlExpr.replace("{" + p + "}", '" + encodeURIComponent(' + p + ') + "');
    urlExpr = urlExpr.replace(/\+ "" $/, "").replace(/ \+ ""/g, "");
    const qs = queryFields.length
      ? "\n  const _qs = new URLSearchParams();" + queryFields.map((f) => "\n  if (" + f.name + " !== undefined) _qs.set(\"" + f.name + "\", String(" + f.name + "));").join("") + "\n  const _q = _qs.toString() ? \"?\" + _qs.toString() : \"\";"
      : "";
    const urlFinal = queryFields.length ? "(" + urlExpr + ") + _q" : urlExpr;
    const opts = ["method: \"" + r.httpMethod + "\""];
    if (bodyFields.length) opts.push("body");
    L.push("export async function " + camel(r.name) + "(" + args.join(", ") + "): Promise<" + ret + "> {" + qs);
    L.push("  return apiFetch(" + urlFinal + ", { " + opts.join(", ") + " });");
    L.push("}\n");
  }
  return L.join("\n");
}

function tplList(ent) {
  const E = ent.name, s = snake(E);
  const metas = ent.fields.map(fieldMeta);
  const primary = metas.find((m) => m.listRole === "primary") || metas[0];
  const secondary = metas.filter((m) => m.listRole === "secondary" && m !== primary);
  const L = [HEADER, '"use client";', 'import { useEffect, useState } from "react";'];
  L.push('import { list' + E + 's } from "../../client/' + s + '";');
  L.push('import type { ' + E + ' } from "../../types/' + s + '";\n');
  L.push("// 優先度カードリスト(全列テーブルにしない): primary を突出、secondary を従属。");
  L.push("export function " + E + "List() {");
  L.push("  const [rows, setRows] = useState<" + E + "[]>([]);");
  L.push("  useEffect(() => { list" + E + "s().then(setRows).catch(() => setRows([])); }, []);");
  L.push("  return (");
  L.push('    <ul style={{ listStyle: "none", padding: 0, display: "grid", gap: 8 }}>');
  L.push("      {rows.map((r) => (");
  L.push('        <li key={r.' + (metas.find((m) => m.isPk)?.name || "id") + '} style={{ border: "1px solid #ddd", borderRadius: 8, padding: 12 }}>');
  L.push('          <div style={{ fontWeight: 700, fontSize: 16 }}>{r.' + primary.name + "}</div>");
  if (secondary.length) {
    L.push('          <div style={{ color: "#666", fontSize: 13 }}>');
    L.push("            " + secondary.map((m) => (m.isTs ? "{new Date(r." + m.name + " * 1000).toLocaleDateString()}" : "{r." + m.name + "}")).join(' <span> · </span> '));
    L.push("          </div>");
  }
  L.push("        </li>");
  L.push("      ))}");
  L.push("    </ul>");
  L.push("  );");
  L.push("}\n");
  return L.join("\n");
}

function tplForm(ent, svc) {
  const E = ent.name, s = snake(E);
  const metas = ent.fields.map(fieldMeta);
  const editable = metas.filter((m) => m.editable);
  const L = [HEADER, '"use client";', 'import { useState } from "react";'];
  L.push('import { create' + E + ' } from "../../client/' + s + '";');
  L.push('import { Field } from "../../../lib/widgets";\n');
  L.push("// 生成フォーム: 編集可能フィールドのみ。validation は @required/@email から生成(entity検証と同源)。");
  L.push("export function " + E + "Form({ onCreated }: { onCreated?: () => void }) {");
  for (const m of editable) L.push("  const [" + m.name + ", set_" + m.name + '] = useState("");');
  L.push("  const [error, setError] = useState<string | null>(null);");
  L.push("  async function submit(e: React.FormEvent) {");
  L.push("    e.preventDefault();");
  // generated validation
  for (const m of editable) {
    if (m.isRequired || m.isEmail) {
      L.push("    if (!" + m.name + ".trim()) { setError(\"" + m.label + " is required\"); return; }");
    }
    if (m.isEmail) {
      L.push("    if (!" + m.name + '.includes("@")) { setError("' + m.label + ' is invalid"); return; }');
    }
  }
  L.push("    setError(null);");
  L.push("    await create" + E + "({ " + editable.map((m) => m.name).join(", ") + " });");
  L.push("    onCreated?.();");
  L.push("  }");
  L.push("  return (");
  L.push('    <form onSubmit={submit} style={{ display: "grid", gap: 8, maxWidth: 360 }}>');
  for (const m of editable) {
    L.push('      <Field label="' + m.label + '" type="' + m.widget + '" value={' + m.name + "} onChange={set_" + m.name + "} />");
  }
  L.push('      {error && <div style={{ color: "crimson", fontSize: 13 }}>{error}</div>}');
  L.push("      <button type=\"submit\">Create</button>");
  L.push("    </form>");
  L.push("  );");
  L.push("}\n");
  return L.join("\n");
}

function tplPage(ent) {
  const E = ent.name, s = snake(E);
  const L = [HEADER, '"use client";', 'import { useState } from "react";'];
  L.push('import { ' + E + 'List } from "../../gen/ui/' + s + '/' + E + 'List";');
  L.push('import { ' + E + 'Form } from "../../gen/ui/' + s + '/' + E + 'Form";\n');
  L.push("export default function " + E + "sPage() {");
  L.push("  const [k, setK] = useState(0);");
  L.push("  return (");
  L.push('    <main style={{ maxWidth: 640, margin: "2rem auto", fontFamily: "system-ui" }}>');
  L.push("      <h1>" + E + "s</h1>");
  L.push("      <" + E + "Form onCreated={() => setK((x) => x + 1)} />");
  L.push('      <hr style={{ margin: "1rem 0" }} />');
  L.push("      <" + E + "List key={k} />");
  L.push("    </main>");
  L.push("  );");
  L.push("}\n");
  return L.join("\n");
}

// ---------- main ----------
function write(rel, content) {
  const dst = join(ROOT, rel);
  mkdirSync(dirname(dst), { recursive: true });
  writeFileSync(dst, content);
  console.log("gen:", rel);
}

const proto = readFileSync(join(ROOT, "proto/user/v1/user.proto"), "utf8");
const model = parseProto(proto);
const msgByName = Object.fromEntries(model.messages.map((m) => [m.name, m]));
for (const svc of model.services) {
  const ent = model.messages.find((m) => "entity" in m.annotations && svc.name.replace(/Service$/, "") === m.name)
    || model.messages.find((m) => "entity" in m.annotations);
  const s = snake(ent.name);
  write("src/gen/types/" + s + ".ts", tplTypes(ent, msgByName));
  write("src/gen/client/" + s + ".ts", tplClient(ent, svc, msgByName));
  write("src/gen/ui/" + s + "/" + ent.name + "List.tsx", tplList(ent));
  write("src/gen/ui/" + s + "/" + ent.name + "Form.tsx", tplForm(ent, svc));
  write("src/app/" + s + "s/page.tsx", tplPage(ent));
}
