// Code generated by mss-protoc-gen. DO NOT EDIT.

package repository

import (
	"context"
	"errors"
	"time"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"

	"{{.ImportEntity}}"
	"{{.ImportRepository}}"
)

type {{.LowerFirst}}Model struct {
{{- range .Fields}}
	{{.GoName}} {{.GoType}} `gorm:"{{gormTag .}}"`
{{- end}}
}

func ({{.LowerFirst}}Model) TableName() string { return "{{.Plural}}" }

func (m *{{.LowerFirst}}Model) toEntity() *entity.{{.Name}} {
	return entity.Hydrate{{.Name}}(
{{- range .Fields}}
		m.{{.GoName}},
{{- end}}
	)
}

func {{.LowerFirst}}ToModel(e *entity.{{.Name}}) *{{.LowerFirst}}Model {
	return &{{.LowerFirst}}Model{
{{- range .Fields}}
		{{.GoName}}: e.{{.GoName}},
{{- end}}
	}
}

type postgres{{.Name}}Repository struct {
	db *gorm.DB
}

func NewPostgres{{.Name}}Repository(db *gorm.DB) repository.{{.Name}}Repository {
	return &postgres{{.Name}}Repository{db: db}
}

// AutoMigrate{{.Name}} は開発用途のスキーマ同期ヘルパー。
// 本番では Goose / Atlas / Flyway 等のマイグレーションツールを使うこと。
func AutoMigrate{{.Name}}(db *gorm.DB) error {
	return db.AutoMigrate(&{{.LowerFirst}}Model{})
}

var _ repository.{{.Name}}Repository = (*postgres{{.Name}}Repository)(nil)
var _ = time.Time{}

func (r *postgres{{.Name}}Repository) SelectAll(ctx context.Context) ([]*entity.{{.Name}}, error) {
	var ms []{{.LowerFirst}}Model
	if err := r.db.WithContext(ctx).Find(&ms).Error; err != nil {
		return nil, err
	}
	out := make([]*entity.{{.Name}}, 0, len(ms))
	for i := range ms {
		out = append(out, ms[i].toEntity())
	}
	return out, nil
}

func (r *postgres{{.Name}}Repository) SelectByPK(ctx context.Context, {{.PKField.ParamName}} {{.PKField.GoType}}) (*entity.{{.Name}}, error) {
	var m {{.LowerFirst}}Model
	err := r.db.WithContext(ctx).Where("{{.PKField.SnakeName}} = ?", {{.PKField.ParamName}}).First(&m).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return m.toEntity(), nil
}
{{range .UniqueFieldsNonPK}}
func (r *postgres{{$.Name}}Repository) SelectBy{{.GoName}}(ctx context.Context, {{.ParamName}} {{.GoType}}) (*entity.{{$.Name}}, error) {
	var m {{$.LowerFirst}}Model
	err := r.db.WithContext(ctx).Where("{{.SnakeName}} = ?", {{.ParamName}}).First(&m).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return m.toEntity(), nil
}
{{end}}
func (r *postgres{{.Name}}Repository) Insert(ctx context.Context, {{.LowerFirst}} *entity.{{.Name}}) error {
	m := {{.LowerFirst}}ToModel({{.LowerFirst}})
	if err := r.db.WithContext(ctx).Create(m).Error; err != nil {
		if errors.Is(err, gorm.ErrDuplicatedKey) {
			return repository.Err{{.Name}}AlreadyExists
		}
		return err
	}
	return nil
}

func (r *postgres{{.Name}}Repository) BulkInsert(ctx context.Context, {{.Plural}} []*entity.{{.Name}}) error {
	if len({{.Plural}}) == 0 {
		return nil
	}
	return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		ms := make([]{{.LowerFirst}}Model, 0, len({{.Plural}}))
		for _, v := range {{.Plural}} {
			ms = append(ms, *{{.LowerFirst}}ToModel(v))
		}
		if err := tx.CreateInBatches(&ms, 100).Error; err != nil {
			if errors.Is(err, gorm.ErrDuplicatedKey) {
				return repository.Err{{.Name}}AlreadyExists
			}
			return err
		}
		return nil
	})
}

func (r *postgres{{.Name}}Repository) Upsert(ctx context.Context, {{.LowerFirst}} *entity.{{.Name}}) error {
	m := {{.LowerFirst}}ToModel({{.LowerFirst}})
	return r.db.WithContext(ctx).Clauses(clause.OnConflict{UpdateAll: true}).Create(m).Error
}

func (r *postgres{{.Name}}Repository) BulkUpsert(ctx context.Context, {{.Plural}} []*entity.{{.Name}}) error {
	if len({{.Plural}}) == 0 {
		return nil
	}
	return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		ms := make([]{{.LowerFirst}}Model, 0, len({{.Plural}}))
		for _, v := range {{.Plural}} {
			ms = append(ms, *{{.LowerFirst}}ToModel(v))
		}
		return tx.Clauses(clause.OnConflict{UpdateAll: true}).CreateInBatches(&ms, 100).Error
	})
}

func (r *postgres{{.Name}}Repository) Update(ctx context.Context, {{.LowerFirst}} *entity.{{.Name}}) error {
	m := {{.LowerFirst}}ToModel({{.LowerFirst}})
	res := r.db.WithContext(ctx).Model(&{{.LowerFirst}}Model{}).Where("{{.PKField.SnakeName}} = ?", m.{{.PKField.GoName}}).Updates(m)
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return repository.Err{{.Name}}NotFound
	}
	return nil
}

func (r *postgres{{.Name}}Repository) Delete(ctx context.Context, {{.PKField.ParamName}} {{.PKField.GoType}}) error {
	res := r.db.WithContext(ctx).Where("{{.PKField.SnakeName}} = ?", {{.PKField.ParamName}}).Delete(&{{.LowerFirst}}Model{})
	if res.Error != nil {
		return res.Error
	}
	if res.RowsAffected == 0 {
		return repository.Err{{.Name}}NotFound
	}
	return nil
}

func (r *postgres{{.Name}}Repository) BulkDelete(ctx context.Context, {{.PKField.ParamName}}s []{{.PKField.GoType}}) error {
	if len({{.PKField.ParamName}}s) == 0 {
		return nil
	}
	return r.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		res := tx.Where("{{.PKField.SnakeName}} IN ?", {{.PKField.ParamName}}s).Delete(&{{.LowerFirst}}Model{})
		if res.Error != nil {
			return res.Error
		}
		if res.RowsAffected != int64(len({{.PKField.ParamName}}s)) {
			return repository.Err{{.Name}}NotFound
		}
		return nil
	})
}

func (r *postgres{{.Name}}Repository) DeleteAll(ctx context.Context) error {
	return r.db.WithContext(ctx).Where("1 = 1").Delete(&{{.LowerFirst}}Model{}).Error
}
