// Code generated by mss-protoc-gen. DO NOT EDIT.

export type {{.Name}}Props = {
{{- range .Fields}}
  {{.name}}: {{.type}};
{{- end}}
};

export class {{.Name}} {
{{- range .Fields}}
  readonly {{.name}}: {{.type}};
{{- end}}

  private constructor(props: {{.Name}}Props) {
{{- range .Fields}}
    this.{{.name}} = props.{{.name}};
{{- end}}
  }

  static create(props: {{.Name}}Props): {{.Name}} {
{{- range .Fields}}
{{- if .isPk}}
    if (!props.{{.name}}) {
      throw new Error("{{.name}} is required");
    }
{{- end}}
{{- if and .isRequired (eq .type "string")}}
    const {{.name}} = props.{{.name}}.trim();
    if (!{{.name}}) {
      throw new Error("{{.name}} is required");
    }
{{- end}}
{{- if .isEmail}}
    const {{.name}} = props.{{.name}}.trim();
    if (!{{.name}} || !{{.name}}.includes("@")) {
      throw new Error("{{.name}} is invalid");
    }
{{- end}}
{{- end}}
    return new {{.Name}}({
{{- range .Fields}}
{{- if or .isEmail (and .isRequired (eq .type "string"))}}
      {{.name}},
{{- else}}
      {{.name}}: props.{{.name}},
{{- end}}
{{- end}}
    });
  }

  /** 永続化層から復元した値で {{.Name}} を組み立てる（バリデーションなし）。通常コードパスでは create() を使うこと。 */
  static hydrate(props: {{.Name}}Props): {{.Name}} {
    return new {{.Name}}(props);
  }
}
