// Code generated by mss-protoc-gen. DO NOT EDIT.

import { asc, eq, gt, inArray } from "drizzle-orm";
import type { NodePgDatabase } from "drizzle-orm/node-postgres";

import { {{.Name}}, {{.Plural}}Table, type {{.Name}}Insert } from "../../domain/entity/{{.Kebab}}.gen.js";
import {
  type {{.Name}}Repository,
  {{.Name}}NotFoundError,
  {{.Name}}AlreadyExistsError,
} from "../../domain/repository/{{.Kebab}}-repository.gen.js";

function rowTo{{.Name}}(r: typeof {{.Plural}}Table.$inferSelect): {{.Name}} {
  return {{.Name}}.hydrate({
{{- range .Fields}}
    {{.name}}: r.{{.name}},
{{- end}}
  });
}

function {{.LowerFirst}}ToRow({{.LowerFirst}}: {{.Name}}): {{.Name}}Insert {
  return {
{{- range .Fields}}
    {{.name}}: {{$.LowerFirst}}.{{.name}},
{{- end}}
  };
}

function isUniqueViolation(err: unknown): boolean {
  return typeof err === "object" && err !== null && (err as { code?: string }).code === "23505";
}

export class Postgres{{.Name}}Repository implements {{.Name}}Repository {
  constructor(private readonly db: NodePgDatabase<Record<string, never>>) {}

  async selectAll(): Promise<{{.Name}}[]> {
    const rows = await this.db.select().from({{.Plural}}Table);
    return rows.map(rowTo{{.Name}});
  }

  async selectByPk({{.PKField.name}}: {{.PKField.type}}): Promise<{{.Name}} | null> {
    const rows = await this.db.select().from({{.Plural}}Table).where(eq({{.Plural}}Table.{{.PKField.name}}, {{.PKField.name}})).limit(1);
    return rows[0] ? rowTo{{.Name}}(rows[0]) : null;
  }
{{range .UniqueFieldsNonPK}}
  async selectBy{{capitalize .name}}({{.name}}: {{.type}}): Promise<{{$.Name}} | null> {
    const rows = await this.db.select().from({{$.Plural}}Table).where(eq({{$.Plural}}Table.{{.name}}, {{.name}})).limit(1);
    return rows[0] ? rowTo{{$.Name}}(rows[0]) : null;
  }
{{end}}
  async insert({{.LowerFirst}}: {{.Name}}): Promise<void> {
    try {
      await this.db.insert({{.Plural}}Table).values({{.LowerFirst}}ToRow({{.LowerFirst}}));
    } catch (e) {
      if (isUniqueViolation(e)) throw new {{.Name}}AlreadyExistsError();
      throw e;
    }
  }

  async bulkInsert({{.Plural}}: {{.Name}}[]): Promise<void> {
    if ({{.Plural}}.length === 0) return;
    await this.db.transaction(async (tx) => {
      try {
        await tx.insert({{.Plural}}Table).values({{.Plural}}.map({{.LowerFirst}}ToRow));
      } catch (e) {
        if (isUniqueViolation(e)) throw new {{.Name}}AlreadyExistsError();
        throw e;
      }
    });
  }

  async upsert({{.LowerFirst}}: {{.Name}}): Promise<void> {
    const row = {{.LowerFirst}}ToRow({{.LowerFirst}});
    await this.db.insert({{.Plural}}Table).values(row).onConflictDoUpdate({
      target: {{.Plural}}Table.{{.PKField.name}},
      set: row,
    });
  }

  async bulkUpsert({{.Plural}}: {{.Name}}[]): Promise<void> {
    if ({{.Plural}}.length === 0) return;
    await this.db.transaction(async (tx) => {
      for (const {{.LowerFirst}} of {{.Plural}}) {
        const row = {{.LowerFirst}}ToRow({{.LowerFirst}});
        await tx.insert({{.Plural}}Table).values(row).onConflictDoUpdate({
          target: {{.Plural}}Table.{{.PKField.name}},
          set: row,
        });
      }
    });
  }

  async update({{.LowerFirst}}: {{.Name}}): Promise<void> {
    const row = {{.LowerFirst}}ToRow({{.LowerFirst}});
    const res = await this.db.update({{.Plural}}Table).set(row).where(eq({{.Plural}}Table.{{.PKField.name}}, {{.LowerFirst}}.{{.PKField.name}}));
    if ((res as { rowCount?: number | null }).rowCount === 0) throw new {{.Name}}NotFoundError();
  }

  async delete({{.PKField.name}}: {{.PKField.type}}): Promise<void> {
    const res = await this.db.delete({{.Plural}}Table).where(eq({{.Plural}}Table.{{.PKField.name}}, {{.PKField.name}}));
    if ((res as { rowCount?: number | null }).rowCount === 0) throw new {{.Name}}NotFoundError();
  }

  async bulkDelete({{.PKField.name}}s: {{.PKField.type}}[]): Promise<void> {
    if ({{.PKField.name}}s.length === 0) return;
    await this.db.transaction(async (tx) => {
      const res = await tx.delete({{.Plural}}Table).where(inArray({{.Plural}}Table.{{.PKField.name}}, {{.PKField.name}}s));
      if ((res as { rowCount?: number | null }).rowCount !== {{.PKField.name}}s.length) throw new {{.Name}}NotFoundError();
    });
  }

  async deleteAll(): Promise<void> {
    await this.db.delete({{.Plural}}Table);
  }
{{- if .HasPaging}}

  async selectByCursor(limit: number, after: {{.PagingField.type}} | null): Promise<{{.Name}}[]> {
    const q = this.db.select().from({{.Plural}}Table).orderBy(asc({{.Plural}}Table.{{.PagingField.name}})).limit(limit);
    const rows = after === null
      ? await q
      : await q.where(gt({{.Plural}}Table.{{.PagingField.name}}, after));
    return rows.map(rowTo{{.Name}});
  }
{{- end}}
}
