// Code generated by mss-protoc-gen. DO NOT EDIT.

import { UserForm } from "../../../gen/ui/user/UserForm";
import { Page } from "../../../lib/widgets";

export default function NewUserPage() {
  return (<Page title="New User"><UserForm /></Page>);
}
