// Code generated by mss-protoc-gen. DO NOT EDIT.

import { UserForm } from "../../../gen/ui/user/UserForm";

export default function NewUserPage() {
  return (<main style={{ maxWidth: 640, margin: "2rem auto", fontFamily: "system-ui" }}><h1>New User</h1><UserForm /></main>);
}
