// Code generated by mss-protoc-gen. DO NOT EDIT.

import type { User } from "../../domain/entity/user.gen.js";
import type { UserRepository } from "../../domain/repository/user-repository.gen.js";

export class InMemoryUserRepository implements UserRepository {
  private readonly items = new Map<string, User>();

  async save(user: User): Promise<void> {
    this.items.set(user.id, user);
  }

  async findById(id: string): Promise<User | null> {
    return this.items.get(id) ?? null;
  }

  async findByEmail(email: string): Promise<User | null> {
    for (const item of this.items.values()) {
      if (item.email === email) return item;
    }
    return null;
  }
}
