// Code generated by mss-protoc-gen. DO NOT EDIT.

package repository

import (
	"context"

	"github.com/example/manji-standard-server-go/pkg/domain/entity"
)

type UserRepository interface {
	Save(ctx context.Context, u *entity.User) error
	FindByID(ctx context.Context, id string) (*entity.User, error)
	FindByEmail(ctx context.Context, email string) (*entity.User, error)
}
