// mss-protoc-gen は proto メッセージから DDD の Entity / Repository interface /
// InMemory Repository 実装を生成するカスタムプラグイン。
//
// アノテーション（proto コメント上に記述）:
//   @entity       メッセージ全体に付与。生成対象とみなす。
//   @pk           フィールドに付与。主キー。FindByID 相当が生成される。
//   @unique       フィールドに付与。FindBy<Field> メソッドが追加で生成される。
//   @email        フィールドに付与。email 形式バリデーション。
//   @required     フィールドに付与。非空バリデーション。
//   @timestamp    int64 フィールドに付与。Entity 側で time.Time にマップされる。
package main

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
)

const (
	goImportEntity     = "github.com/example/manji-standard-server-go/pkg/domain/entity"
	goImportRepository = "github.com/example/manji-standard-server-go/pkg/domain/repository"
	goImportInfraRepo  = "github.com/example/manji-standard-server-go/pkg/infra/repository"
)

type fieldSpec struct {
	GoName      string // PascalCase (ID, Email)
	ParamName   string // camelCase (id, email)
	SnakeName   string // snake_case (id, created_at)
	ProtoType   string // proto 型名 (string, int64)
	GoType      string // Entity 側の Go 型
	IsPK        bool
	IsUnique    bool
	IsEmail     bool
	IsRequired  bool
	IsTimestamp bool
}

type entitySpec struct {
	Name         string // "User"
	SnakeName    string // "user"
	Fields       []fieldSpec
	PKField      *fieldSpec
	UniqueFields []fieldSpec
}

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			for _, msg := range f.Messages {
				e := parseEntity(msg)
				if e == nil {
					continue
				}
				generateEntity(gen, e)
				generateRepository(gen, e)
				generateInfraRepository(gen, e)
			}
		}
		return nil
	})
}

// parseEntity はメッセージが @entity マーカーを持つ場合に entitySpec を返す。
// そうでない場合は nil。
func parseEntity(msg *protogen.Message) *entitySpec {
	if !hasMarker(string(msg.Comments.Leading), "@entity") {
		return nil
	}
	name := msg.GoIdent.GoName
	snake := toSnake(name)
	e := &entitySpec{Name: name, SnakeName: snake}

	for _, f := range msg.Fields {
		comment := string(f.Comments.Leading)
		goName := normalizeInitialisms(f.GoName)
		paramName := lowerFirst(f.GoName) // 引数名は元の lowerFirst（id, email など）
		snakeField := toSnake(f.GoName)

		spec := fieldSpec{
			GoName:      goName,
			ParamName:   paramName,
			SnakeName:   snakeField,
			ProtoType:   f.Desc.Kind().String(),
			IsPK:        hasMarker(comment, "@pk"),
			IsUnique:    hasMarker(comment, "@unique"),
			IsEmail:     hasMarker(comment, "@email"),
			IsRequired:  hasMarker(comment, "@required"),
			IsTimestamp: hasMarker(comment, "@timestamp"),
		}

		// Go 型決定
		switch {
		case spec.IsTimestamp:
			spec.GoType = "time.Time"
			// タイムスタンプフィールド名 from "created_at_unix" → "CreatedAt" / "createdAt"
			trimmed := strings.TrimSuffix(spec.GoName, "Unix")
			spec.GoName = trimmed
			spec.ParamName = lowerFirst(trimmed)
			spec.SnakeName = toSnake(trimmed)
		case spec.ProtoType == "string":
			spec.GoType = "string"
		case spec.ProtoType == "int32":
			spec.GoType = "int32"
		case spec.ProtoType == "int64":
			spec.GoType = "int64"
		case spec.ProtoType == "bool":
			spec.GoType = "bool"
		default:
			spec.GoType = "string" // フォールバック
		}

		e.Fields = append(e.Fields, spec)
		if spec.IsPK {
			pk := spec
			e.PKField = &pk
		}
		if spec.IsUnique {
			e.UniqueFields = append(e.UniqueFields, spec)
		}
	}

	if e.PKField == nil {
		// PK 指定がないメッセージはエンティティ扱いしない
		return nil
	}
	return e
}

// ==================== Entity 生成 ====================

func generateEntity(gen *protogen.Plugin, e *entitySpec) {
	filename := fmt.Sprintf("pkg/domain/entity/%s.gen.go", e.SnakeName)
	g := gen.NewGeneratedFile(filename, goImportEntity)

	g.P("// Code generated by mss-protoc-gen. DO NOT EDIT.")
	g.P()
	g.P("package entity")
	g.P()
	g.P("import (")
	g.P(`	"errors"`)
	g.P(`	"strings"`)
	g.P(`	"time"`)
	g.P(")")
	g.P()

	// struct
	g.P("type ", e.Name, " struct {")
	for _, f := range e.Fields {
		g.P("	", f.GoName, " ", f.GoType)
	}
	g.P("}")
	g.P()

	// factory
	g.P("func New", e.Name, "(")
	for i, f := range e.Fields {
		comma := ","
		if i == len(e.Fields)-1 {
			comma = ","
		}
		g.P("	", f.ParamName, " ", f.GoType, comma)
	}
	g.P(") (*", e.Name, ", error) {")

	for _, f := range e.Fields {
		if f.IsPK {
			g.P(`	if `, f.ParamName, ` == "" {`)
			g.P(`		return nil, errors.New("`, f.SnakeName, ` is required")`)
			g.P(`	}`)
		}
		if f.IsRequired && f.GoType == "string" {
			g.P(`	`, f.ParamName, ` = strings.TrimSpace(`, f.ParamName, `)`)
			g.P(`	if `, f.ParamName, ` == "" {`)
			g.P(`		return nil, errors.New("`, f.SnakeName, ` is required")`)
			g.P(`	}`)
		}
		if f.IsEmail {
			g.P(`	`, f.ParamName, ` = strings.TrimSpace(`, f.ParamName, `)`)
			g.P(`	if `, f.ParamName, ` == "" || !strings.Contains(`, f.ParamName, `, "@") {`)
			g.P(`		return nil, errors.New("`, f.SnakeName, ` is invalid")`)
			g.P(`	}`)
		}
	}

	g.P("	return &", e.Name, "{")
	for _, f := range e.Fields {
		g.P("		", f.GoName, ": ", f.ParamName, ",")
	}
	g.P("	}, nil")
	g.P("}")
	g.P()

	// 使わない警告対策: time は IsTimestamp フィールドがなくても import しているので参照
	g.P("var _ = time.Time{}")
}

// ==================== Repository interface 生成 ====================

func generateRepository(gen *protogen.Plugin, e *entitySpec) {
	filename := fmt.Sprintf("pkg/domain/repository/%s_repository.gen.go", e.SnakeName)
	g := gen.NewGeneratedFile(filename, goImportRepository)

	g.P("// Code generated by mss-protoc-gen. DO NOT EDIT.")
	g.P()
	g.P("package repository")
	g.P()
	g.P("import (")
	g.P(`	"context"`)
	g.P()
	g.P(`	"`, goImportEntity, `"`)
	g.P(")")
	g.P()

	g.P("type ", e.Name, "Repository interface {")
	g.P("	Save(ctx context.Context, ", strings.ToLower(string(e.Name[0])), " *entity.", e.Name, ") error")
	g.P("	FindBy", e.PKField.GoName, "(ctx context.Context, ", e.PKField.ParamName, " ", e.PKField.GoType, ") (*entity.", e.Name, ", error)")
	for _, u := range e.UniqueFields {
		if u.IsPK {
			continue
		}
		g.P("	FindBy", u.GoName, "(ctx context.Context, ", u.ParamName, " ", u.GoType, ") (*entity.", e.Name, ", error)")
	}
	g.P("}")
}

// ==================== Infra Repository 実装生成 ====================

func generateInfraRepository(gen *protogen.Plugin, e *entitySpec) {
	filename := fmt.Sprintf("pkg/infra/repository/%s_repository.gen.go", e.SnakeName)
	g := gen.NewGeneratedFile(filename, goImportInfraRepo)

	recv := strings.ToLower(string(e.Name[0]))
	pkField := e.PKField

	g.P("// Code generated by mss-protoc-gen. DO NOT EDIT.")
	g.P()
	g.P("package repository")
	g.P()
	g.P("import (")
	g.P(`	"context"`)
	g.P(`	"sync"`)
	g.P()
	g.P(`	"`, goImportEntity, `"`)
	g.P(`	"`, goImportRepository, `"`)
	g.P(")")
	g.P()

	structName := "inMemory" + e.Name + "Repository"
	g.P("type ", structName, " struct {")
	g.P("	mu    sync.RWMutex")
	g.P("	items map[", pkField.GoType, "]*entity.", e.Name)
	g.P("}")
	g.P()

	g.P("func NewInMemory", e.Name, "Repository() repository.", e.Name, "Repository {")
	g.P("	return &", structName, "{items: make(map[", pkField.GoType, "]*entity.", e.Name, ")}")
	g.P("}")
	g.P()

	// Save
	g.P("func (r *", structName, ") Save(_ context.Context, ", recv, " *entity.", e.Name, ") error {")
	g.P("	r.mu.Lock()")
	g.P("	defer r.mu.Unlock()")
	g.P("	r.items[", recv, ".", pkField.GoName, "] = ", recv)
	g.P("	return nil")
	g.P("}")
	g.P()

	// FindByPK
	g.P("func (r *", structName, ") FindBy", pkField.GoName, "(_ context.Context, ", pkField.ParamName, " ", pkField.GoType, ") (*entity.", e.Name, ", error) {")
	g.P("	r.mu.RLock()")
	g.P("	defer r.mu.RUnlock()")
	g.P("	v, ok := r.items[", pkField.ParamName, "]")
	g.P("	if !ok {")
	g.P("		return nil, nil")
	g.P("	}")
	g.P("	return v, nil")
	g.P("}")
	g.P()

	// FindBy<Unique>
	for _, u := range e.UniqueFields {
		if u.IsPK {
			continue
		}
		g.P("func (r *", structName, ") FindBy", u.GoName, "(_ context.Context, ", u.ParamName, " ", u.GoType, ") (*entity.", e.Name, ", error) {")
		g.P("	r.mu.RLock()")
		g.P("	defer r.mu.RUnlock()")
		g.P("	for _, v := range r.items {")
		g.P("		if v.", u.GoName, " == ", u.ParamName, " {")
		g.P("			return v, nil")
		g.P("		}")
		g.P("	}")
		g.P("	return nil, nil")
		g.P("}")
		g.P()
	}
}

// ==================== helpers ====================

func hasMarker(comment, marker string) bool {
	for _, line := range strings.Split(comment, "\n") {
		line = strings.TrimSpace(line)
		line = strings.TrimPrefix(line, "//")
		for _, tok := range strings.Fields(line) {
			if tok == marker {
				return true
			}
		}
	}
	return false
}

// normalizeInitialisms: Go style guide に合わせて既知の頭字語を大文字化する。
//   例: "Id" → "ID", "UserId" → "UserID", "ApiKey" → "APIKey"
func normalizeInitialisms(s string) string {
	repl := map[string]string{
		"Id":   "ID",
		"Url":  "URL",
		"Api":  "API",
		"Http": "HTTP",
		"Json": "JSON",
		"Xml":  "XML",
	}
	for from, to := range repl {
		// 完全一致
		if s == from {
			return to
		}
		// 末尾一致（直前が小文字なら単語の終わり）
		if strings.HasSuffix(s, from) && len(s) > len(from) {
			prev := s[len(s)-len(from)-1]
			if prev >= 'a' && prev <= 'z' {
				s = s[:len(s)-len(from)] + to
			}
		}
	}
	return s
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(string(s[0])) + s[1:]
}

// toSnake: PascalCase/camelCase → snake_case
func toSnake(s string) string {
	var b strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			b.WriteByte('_')
		}
		if r >= 'A' && r <= 'Z' {
			b.WriteRune(r + 32)
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}
