// Code generated by mss-protoc-gen. DO NOT EDIT.

package usecase

import (
	"context"
{{if .AnyReturnsEntity}}
	"{{.ImportEntity}}"
{{end}}
)
{{range .Methods}}
{{- if .HasInputFields}}

type {{.InputTypeName}} struct {
{{- range .InputFields}}
	{{.GoName}} {{.GoType}}
{{- end}}
}
{{- else}}

type {{.InputTypeName}} struct{}
{{- end}}
{{- end}}

// {{.UsecaseTypeName}} は {{.ServiceName}} の rpc 1 本につき 1 メソッドを持つ interface。
// 実装クラス（<Name>UsecaseImpl）はこの interface を実装する手書き層。
type {{.UsecaseTypeName}} interface {
{{- range .Methods}}
{{- if .ReturnsEntity}}
	{{.Name}}(ctx context.Context, input {{.InputTypeName}}) (*entity.{{.EntityGoName}}, error)
{{- else if .ReturnsList}}
	{{.Name}}(ctx context.Context, input {{.InputTypeName}}) ([]*entity.{{.EntityGoName}}, error)
{{- else}}
	{{.Name}}(ctx context.Context, input {{.InputTypeName}}) error
{{- end}}
{{- end}}
}
