// Code generated by mss-protoc-gen. DO NOT EDIT.

import type { {{.Name}} } from "../entity/{{.Kebab}}.gen.js";

export class {{.Name}}NotFoundError extends Error {
  constructor() {
    super("{{.LowerFirst}} not found");
    this.name = "{{.Name}}NotFoundError";
  }
}

export class {{.Name}}AlreadyExistsError extends Error {
  constructor() {
    super("{{.LowerFirst}} already exists");
    this.name = "{{.Name}}AlreadyExistsError";
  }
}

export interface {{.Name}}Repository {
  selectAll(): Promise<{{.Name}}[]>;
  selectByPk({{.PKField.name}}: {{.PKField.type}}): Promise<{{.Name}} | null>;
{{- range .UniqueFieldsNonPK}}
  selectBy{{capitalize .name}}({{.name}}: {{.type}}): Promise<{{$.Name}} | null>;
{{- end}}
  insert({{.LowerFirst}}: {{.Name}}): Promise<void>;
  bulkInsert({{.Plural}}: {{.Name}}[]): Promise<void>;
  upsert({{.LowerFirst}}: {{.Name}}): Promise<void>;
  bulkUpsert({{.Plural}}: {{.Name}}[]): Promise<void>;
  update({{.LowerFirst}}: {{.Name}}): Promise<void>;
  delete({{.PKField.name}}: {{.PKField.type}}): Promise<void>;
  bulkDelete({{.PKField.name}}s: {{.PKField.type}}[]): Promise<void>;
  deleteAll(): Promise<void>;
{{- if .HasPaging}}
  selectByCursor(limit: number, after: {{.PagingField.type}} | null): Promise<{{.Name}}[]>;
{{- end}}
}
