// Code generated by mss-protoc-gen. DO NOT EDIT.

import "@/lib/container"; // side-effect: HandlerDeps factory を登録
import { NextResponse } from "next/server";


import {
  UserNotFoundError,
  UserAlreadyExistsError,
} from "@/domain/repository/user-repository.gen";
import { getHandlerDeps } from "@/lib/handler-registry.gen";
import type {
  UserUsecase,
  ListUsersByCursorInput,
  CreateUserParams,
  UpsertUserParams,
} from "@/usecase/user-usecase-interface.gen";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function toHttpError(err: unknown): NextResponse {
  if (err instanceof UserNotFoundError) return NextResponse.json({ error: err.message }, { status: 404 });
  if (err instanceof UserAlreadyExistsError) return NextResponse.json({ error: err.message }, { status: 409 });
  const message = err instanceof Error ? err.message : "unknown error";
  return NextResponse.json({ error: message }, { status: 400 });
}


export async function GET(
  req: Request,
) {
  const searchParams = new URL(req.url).searchParams;
  try {
    const deps = getHandlerDeps();
    const input: ListUsersByCursorInput = {
      limit: Number(searchParams.get("limit") ?? "0"),
      afterId: searchParams.get("after_id") ?? "",
    };
    const list = await deps.userUsecase.listUsersByCursor(input);
    return NextResponse.json(list, { status: 200 });
  } catch (err) {
    return toHttpError(err);
  }
}
